

const lenten = {
  'data': 'lenten',
  'mini' : false,
  'cat': {"EN":'Lenten',"RU":'Постное'},
  'items': [
      {
          id: 91,
          name:{'EN': 'Baked yams with mushrooms and zazaki sauce', 'RU':"Запеченный батат с грибами и соусом дзадзики"},
          title:{'EN': 'Batat, mushrooms, oyster mushrooms, ceps, vegetable oil, garlic puree, cucumbers, lean sour cream, olive oil, truffle oil, pearl onions, green onions, ground olives, dill, salt, pepper, thyme', 'RU':"Батат, шампиньоны, вешенки, белые грибы, масло растительное, чесночное пюре, огурцы, постная сметана, масло оливковое, масло трюфельное, жемчужный лук, лук зеленый, земля из маслин, укроп, соль, перец, тимьян"},
          price: 590,
          count: 1,
          grams: 270,
          img: "https://eda.yandex.ru/images/3208959/0228a35b95534b8e8a2a9b3f66b1e0b4-450x300.jpeg",
        },  {
          id: 92,
          name:{'EN': 'Pistachio cream with coconut milk', 'RU':"Фисташковый крем на кокосовом молоке"},
          title:{'EN': 'Cream of coconut, pistachio paste, powdered sugar, lean cookie crumb, blueberries, freeze-dried raspberries, sunflower seeds', 'RU':"Сливки из кокоса, фисташковая паста, сахарная пудра, крошка из постного печенья, голубика, малина сублимированная, семечка подсолнечника"},
          price: 370,
          count: 1,
          grams: 120,
          img: "https://eda.yandex.ru/images/3337779/dba9330876324cf2b9fc5837dc33ad9f-450x300.jpeg",
        },  {
          id: 93,
          name:{'EN': 'Baked zucchini with beet coulis', 'RU':"Печёный кабачок со свекольным кули"},
          title:{'EN': 'Beets, avocado, mint, cilantro, zucchini, mini spinach, chuka, borado bread chips, kimchi sesame, garlic fraiche, lean sour cream, pumpkin puree, sunflower seeds, olive oil ground, olive oil, salt, pepper, zatar, honey', 'RU':"Свекла, авокадо, мята, кинза, кабачки, мини шпинат, чука, чипсы из бородинского хлеба, кунжут с кимчи, чесночный фреш, сметана постная, пюре тыквы, семечки подсолнечника, земля из маслин, масло оливковое, соль, перец, затар, мёд"},
          price: 570,
          count: 1,
          grams: 225,
          img: "https://eda.yandex.ru/images/3667559/f78601f42dd94e2fa9788763a06550f2-450x300.jpeg",
        }, {
          id: 94,
          name:{'EN': 'Vegetable salad with your choice of dressing', 'RU':"Овощной салат с заправкой на выбор"},
          title:{'EN': 'Cucumber, tomato, bell pepper, parsley, dill, green onion, fresh basil, red onion, tajas olives, olive oil, salt, black pepper, provan herbs', 'RU':"Огурец, помидор, болгарский перец, петрушка, укроп, лук зелёный, базилик свежий, лук красный, оливки таджасские, масло оливковое, соль, перец черный, прованские травы"},
          price: 590,
          modifier: {
            'RU':[
              'c оливковым маслом',
              'c ароматным маслом',
              'c постной сметаной: 100₽'
            ],
            'EN': [
              'with olive oil',
              'with fragrant oil',
              'with lean sour cream: 100₽'
            ]
          },
          count: 1,
          grams: 188,
          img: "https://eda.yandex.ru/images/3724421/cd721dd431634672b6980a0c65df1da0-450x300.jpeg",
        },  {
          id: 95,
          name:{'EN': 'Lentil cream soup with artichokes and pickled onions', 'RU':"Крем-суп из чечевицы с артишоками и маринованным лучком"},
          title:{'EN': 'Lentils, carrots, onions, potatoes, artichokes, pearl onions, green onions, seeds, ground olives, olive oil, vegetable oil, garlic, salt, pepper', 'RU':"Чечевица, морковь, лук репчатый, картофель, артишоки, лук жемчужный, лук зеленый, семечки, земля из маслин, оливковое масло, масло растительное, чеснок, соль, перец"},
          price: 420,
          count: 1,
          grams: 330,
          img: "https://eda.yandex.ru/images/3580810/96ad18ccda1d42e3b3949d156dbe14f1-450x300.jpeg",
        },
        {
          id: 96,
          name:{'EN': 'Hummus with grilled broccoli', 'RU':"Хумус с брокколи гриль"},
          title:{'EN': 'Chickpeas, tahini, ground cumin, lemon juice, broccoli, olive oil, sea salt, slivered almonds, zatar, sesame oil, sunflower and pumpkin seeds, microgreens', 'RU':"Нут, тахини, кумин молотый, лимонный сок, брокколи, масло оливковое, соль морская, миндаль слайс, затар, масло кунжутное, семечка подсолничника и тыквы, микрозелень"},
          price: 490,
          count: 1,
          grams: 270,
          img: "https://eda.yandex.ru/images/3106738/aa1e9c65855440c8bfc59cc905a5db77-450x300.jpeg",
        },
        {
          id: 97,
          name:{'EN': 'Crispy falafel with babaganoush, dzadziki and fresh tomatoes', 'RU':"Хрустящий фалафель с бабагануш, дзадзики и свежими томатами"},
          title:{'EN': 'Chickpeas, spinach, truffle paste, truffle oil, breadcrumbs, wheat flour, coconut milk, baked eggplant, tomatoes, cilantro, parsley, green onions, garlic puree, cucumber, lean sour cream, olive seeds, tomatoes, basil, black pepper, zatar, olive oil, salt', 'RU':"Нут, шпинат, трюфельная паста, масло трюфельное, панировочные сухари, мука пшеничная, молоко кокосовое, баклажан печёный, томаты, кинза, петрушка, лук зелёный, чесночное пюре, огурец, постная сметана, земля из маслин, помидоры, базилик, перец черный, затар, масло оливковое, соль"},
          price: 690,
          count: 1,
          grams: 340,
          img: "https://eda.yandex.ru/images/3682162/00c3527cf7ee4de79f4ef93660ff3ed9-450x300.jpeg",
        }
  ]
}

const items = [ 
  {
    'data' : 'breakfast',
    'mini' : false,
    'cat':{"EN":'Breakfasts until 14:00',"RU":'Завтраки до 14:00'}, 
    'items': [
      
          {
            id: 15,
            name:{'EN': 'Zucchini dredges with salmon and cream sauce', 'RU':"Драники из цукини с лососем и сливочным соусом"} ,
            title:{'EN': 'Zucchini, egg, lightly salted salmon, cream sauce', 'RU':"Цукини, яйцо, лосось слабосоленый, соус сливочный"},
            price: 730,
            count: 1,
            grams: 160,
            img: "https://avatars.mds.yandex.net/get-eda/2050703/d0fe6a0797b741d1bf85f7b40e079136/450x300",
          },
          {
            id: 16,
            name:{'EN': 'Scramble with prosciutto and tomatoes', 'RU':"Скрамбл с прошутто и помидорами"},
            title:{'EN': 'Chicken eggs, prosciutto, tomatoes', 'RU':"Яйца куриные, прошутто, помидоры"},
            price: 490,
            count: 1,
            grams: 140,
            img: "https://avatars.mds.yandex.net/get-eda/3813301/2309447194f24bc482ee55189d530799/450x300",
          },
          
          {
            id: 18,
            name:{'EN': 'Eggs Benedict with salmon on a brioche bun', 'RU':"Яйцо бенедикт с лососем на булочке бриошь"},
            title:{'EN': 'Brioche bun, lightly salted salmon, chicken egg, hollandaise sauce', 'RU':"Булочка бриошь, лосось слабосоленый, яйцо куриное, соус голландский"},
            price: 690,
            count: 1,
            grams: 220,
            img: "https://avatars.mds.yandex.net/get-eda/2353725/9084d606a70e418b9e0a52ce76e08f80/450x300",
          },
          {
            id: 'z1',
            name:{'EN': 'Rice porridge with coconut milk and fresh berries', 'RU':"Рисовая каша на кокосовом молоке со свежими ягодами"},
            title:{'EN': 'Rice, milk, coconut milk, sugar, salt, vanilla sugar, cream, cherry topping, raspberries, blackberries, strawberries, blueberries', 'RU':"Рис, молоко, молоко кокосовое, сахар, соль, ванильный сахар, сливки, топпинг вишневый, малина, ежевика, клубника, голубика"},
            price: 540,
            count: 1,
            grams: 260,
            img: "/assets/items/z1.jpeg",
          },
          {
            id: 'z2',
            name:{'EN': 'Buckwheat porridge with poached egg and parmesan', 'RU':"Гречневая каша с яйцом пашот и пармезаном"},
            title:{'EN': 'Buckwheat, fried onions, butter, soy sauce, grana cheese, green onions, pâté, truffle paste, truffle hollandaise, microgreens, olive ground, truffle oil', 'RU':"Гречка, лук жареный, масло сливочное, соевый соус, грана сыр, лук зеленый, пашот, паста трюфельная, голландез трюфельный, микрозелень, земля из маслин, масло трюфельное"},
            price: 510,
            count: 1,
            grams: 370,
            img: "/assets/items/z2.jpeg",
          },{
            id: 'z3',
            name:{'EN': 'Omelet with crab and truffle sauce', 'RU':"Омлет с крабом и трюфельным соусом"},
            title:{'EN': 'Egg, cream, salt, pepper, corn, grana cheese, truffle oil, crab, green onions, truffle sauce', 'RU':"Яйцо, сливки, соль, перец, корн, сыр грана, масло трюфельное, краб, зеленый лук, трюфельный соус"},
            price: 840,
            count: 1,
            grams: 220,
            img: "/assets/items/z3.jpeg",
          },{
            id: 'z4',
            name:{'EN': 'Eggs Benedict with bacon and truffle hollandaise', 'RU':"Яйцо бенедикт с беконом и трюфельным голландез"},
            title:{'EN': 'Brioche, guacamole, corn, pickled tomatoes, bacon, hollandaise sauce, truffle oil, olive oil', 'RU':"Бриошь, гуакамоле, корн, помидоры маринованные, бекон, соус голландез, масло трюфельное, оливковое масло"},
            price: 490,
            count: 1,
            grams: 175,
            img: "/assets/items/z4.jpeg",
          },
         
          {
            id: 22,
            name:{'EN': 'Cheesecakes with melted milk and sour cream', 'RU':"Сырники из топленого молока со сметаной"} ,
            title:{'EN': 'Cottage cheese, flour, chicken egg, sour cream', 'RU':"Творог, мука, яйцо куриное, сметана"} ,
            price: 360,
            count: 1,
            grams: 170,
            img: "",
          },
        
    ]
  },
  {
    'data' : 'rawbar',
    'mini' : false,
    'cat' : {"EN":'RAW BAR',"RU":'RAW BAR'},
    'items': [
        {
            id: 48,
            name:{'EN':'Sea urchin', 'RU':"Морской ёж"}, 
            title:{'EN':'Sea urchin, quail egg yolk, Ponzu sauce(1pc.)', 'RU':"Морской ёж, желток перепелиного яйца, соус Понзу(1шт.)"}, 
            price: 370,
            count: 1,
            grams: 10,
            img: "https://avatars.mds.yandex.net/get-eda/3805363/82fc446f3def42d7bdf6a79840d52018/450x300",
          },
          {
            id: 52,
            name:{'EN':'Imperial Oyster', 'RU':"Устрица императорская"}, 
            title:{'EN':'Oyster, lemon, wine sauce (1 unit)', 'RU':"Устрица, лимон, соус Винный (1шт.)"}, 
            price: 360,
            count: 1,
            grams: 10,
            img: "https://avatars.mds.yandex.net/get-eda/3506804/3ba638771e994e14be16bbd17fd88590/450x300",
          },
          {
            id: 53,
            name:{'EN':'Oyster Pink Jolie', 'RU':"Устрица Розовая Джоли"},
            title:{'EN':'Oyster, lemon, wine sauce (1 unit)', 'RU':"Устрица, лимон, соус Винный (1шт.)"}, 
            price: 520,
            count: 1,
            grams: 10,
            img: "https://avatars.mds.yandex.net/get-eda/3781088/56f84fb3422f4c688bc61cb1a893c2c5/450x300",
          },
          {
            id: 54,
            name:{'EN':'Khasan Oyster', 'RU':"Устрица Хасанская"}, 
            title:{'EN':'Oyster, lemon, wine sauce (1 unit)', 'RU':"Устрица, лимон, соус Винный (1шт.)"}, 
            price: 360,
            count: 1,
            grams: 10,
            img: "https://avatars.mds.yandex.net/get-eda/3378693/2f86c58f9fa14d4d957448168544b397/450x300",
          },
          {
            id: 49,
            name:{'EN':'Beef tartar', 'RU':"Тартар из говядины"}, 
            title:{'EN':'Beef loin, capers, mustard, tabasco, olive oil, croutons', 'RU':"Говяжья вырезка, каперсы, горчица, табаско, оливковое масло, гренки"},
            price: 920,
            count: 1,
            grams: 160,
            img: "https://avatars.mds.yandex.net/get-eda/3702558/efbdfaa6e41a44e381e6d08b932357ec/450x300",
          },
          {
            id: 50,
            name:{'EN':'Salmon and avocado tartare', 'RU':"Тартар из лосося и авокадо"}, 
            title:{'EN':'Salmon fillet, avocado, sesame, olive oil, ponzu sauce, strawberries', 'RU':"Филе лосося, авокадо, кунжут, оливковое масло, соус понзу, клубника"},
            price: 720,
            count: 1,
            grams: 190,
            img: "https://avatars.mds.yandex.net/get-eda/3774488/873d863faa0f45789ce2dba5393d6c05/450x300",
          },
          {
            id: 51,
            name:{'EN':'Tuna tartar', 'RU':"Тартар из тунца"}, 
            title:{'EN':'Tuna fillet, avocado, guacamole, sesame oil, soy sauce', 'RU':"Филе тунца, авокадо, гуакамоле, кунжутное масло, соевый соус"}, 
            price: 720,
            count: 1,
            grams: 200,
            img: "https://avatars.mds.yandex.net/get-eda/3436037/74e45e0bf868433489bc5e9545a634f0/450x300",
          },
    ]
  },
  {
    'data': 'susi',
    'mini': true,
    'cat':{"EN":'Sushi',"RU":'Суши'},
    items: [
        {
          id: 1,
          name:{'EN': 'Sashimi Shrimp', 'RU': 'Сашими креветка'},
          title: {'EN': 'Shrimp, wasabi, ginger', 'RU':"Креветка, васаби, имбирь"},
          price: 780,
          count: 1,
          grams: 60,
          img: "",
        },
        {
          id: 2,
          name:{'EN': 'Salmon Sashimi', 'RU': "Сашими лосось"},
          title:{'EN': 'Salmon, wasabi, ginger', 'RU': "Лосось, васаби, имбирь"},
          price: 820,
          count: 1,
          grams: 60,
          img: "",
        },
        {
          id: 3,
          name:{'EN': 'Tuna Sashimi', 'RU': "Сашими тунец"},
          title:{'EN': 'Tuna, wasabi, ginger', 'RU': "Тунец, васаби, имбирь"},
          price: 920,
          count: 1,
          grams: 60,
          img: "",
        },
        {
          id: 4,
          name:{'EN': 'Sashimi eel', 'RU': "Сашими угорь"},
          price: 920,
          count: 1,
          grams: 60,
          img: "",
        },
        {
          id: 5,
          name:{'EN': 'Spicy crab', 'RU': "Спайси с крабом"},
          title:{'EN': 'Crab, rice, nori, spicy sauce', 'RU': "Краб, рис, нори, спайси соус"},
          price: 310,
          count: 1,
          grams: 35,
          img: "",
        },
        {
          id: 6,
          name:{'EN': 'Spicy shrimp', 'RU': "Спайси с креветкой"},
          title:{'EN': 'Shrimp, rice, nori, spicy sauce', 'RU': "Креветка, рис, нори, спайси соус"},
          price: 240,
          count: 1,
          grams: 35,
          img: "",
        },
        {
          id: 7,
          name:{'EN': 'Spicy salmon', 'RU': "Спайси с лососем"},
          title:{'EN': 'Salmon, rice, nori, spicy sauce', 'RU': "Лосось, рис, нори, спайси соус"},
          price: 240,
          count: 1,
          grams: 35,
          img: "",
        },
        {
          id: 8,
          name:{'EN': 'Spicy tuna', 'RU': "Спайси с тунцом"},
          title:{'EN': 'Tuna, rice, nori, spicy sauce', 'RU': "Тунец, рис, нори, спайси соус"},
          price: 310,
          count: 1,
          grams: 35,
          img: "",
        },
        {
          id: 9,
          name:{'EN': 'Spicy with eels', 'RU': "Спайси с угрем"},
          title:{'EN': 'Eel, rice, nori, spicy sauce', 'RU': "Угорь, рис, нори, спайси соус"},
          price: 310,
          count: 1,
          grams: 35,
          img: "",
        },
        {
          id: 10,
          name:{'EN': 'Sushi with shrimp', 'RU': "Суши с креветкой"},
          title:{'EN': 'Shrimp, rice', 'RU': "Креветка, рис"},
          price: 240,
          count: 1,
          grams: 30,
          img: "",
        },
        {
          id: 11,
          name:{'EN': 'Sushi with salmon', 'RU': "Суши с лососем"},
          title:{'EN': 'Salmon, rice', 'RU': "Лосось, рис"},
          price: 210,
          count: 1,
          grams: 30,
          img: "",
        },
        {
          id: 12,
          name:{'EN': 'Sushi with tuna', 'RU': "Суши с тунцом"},
          title:{'EN': 'Tuna, rice', 'RU': "Тунец, рис"},
          price: 270,
          count: 1,
          grams: 30,
          img: "",
        },
        {
          id: 13,
          name:{'EN': 'Sushi with eel', 'RU': "Суши с угрем"},
          title:{'EN': 'Eel, rice', 'RU': "Угорь, рис"},
          price: 270,
          count: 1,
          grams: 30,
          img: "",
        },
      ]
  },
  {
    'data' : 'roll',
    'mini' : true,
    'cat':{"EN":'Rolls',"RU":'Роллы'},
    'items': [
        {
            id: 24,
            name: {'EN': 'Maki and avocado', 'RU': "Маки с авокадо"},
            title:{'EN': 'Avocado, rice, nori', 'RU': "Авокадо, рис, нори"},
            price: 310,
            count: 1,
            grams: 100,
            img: "",
          },
          {
            id: 25,
            name:{'EN': 'Maki with salmon', 'RU': "Маки с лососем"},
            title:{'EN': 'Salmon, rice, nori', 'RU': "Лосось, рис, нори"},
            price: 370,
            count: 1,
            grams: 100,
            img: "",
          },
          {
            id: 26,
            name:{'EN': 'Poppies with cucumber', 'RU': "Маки с огурцом"},
            title:{'EN': 'Cucumber, rice, nori', 'RU': "Огурец, рис, нори"},
            price: 260,
            count: 1,
            grams: 100,
            img: "",
          },
          {
            id: 27,
            name:{'EN': 'Tuna maki', 'RU': "Маки с тунцом"} ,
            title:{'EN': 'Tuna, rice, nori', 'RU': "Тунец, рис, нори"} ,
            price: 410,
            count: 1,
            grams: 100,
            img: "",
          },
          {
            id: 28,
            name:{'EN': 'Poppies with eel', 'RU': "Маки с угрем"},
            title:{'EN': 'Eel, rice, nori', 'RU': "Угорь, рис, нори"},
            price: 410,
            count: 1,
            grams: 100,
            img: "",
          },
          {
            id: 29,
            name:{'EN': 'California Roll', 'RU': "Ролл Калифорния"} ,
            title:{'EN': 'Crab, rice, Japanese mayonnaise, avocado, nori, tobiko', 'RU': "Краб, рис, японский майонез, авокадо, нори, тобико"},
            price: 910,
            count: 1,
            grams: 190,
            img: "",
          },
          {
            id: 30,
            name:{'EN': 'Roll Canada', 'RU': "Ролл Канада"} ,
            title:{'EN': 'Salmon, eel, cream cheese, avocado, nori, unagi yuzu sauce, sesame, rice', 'RU': "Лосось, угорь, сливочный сыр, авокадо, нори, соус унаги юдзу, кунжут, рис"},
            price: 1020,
            count: 1,
            grams: 200,
            img: "",
          },
          {
            id: 31,
            name:{'EN': 'Philadelphia Roll', 'RU': "Ролл Филадельфия"},
            title:{'EN': 'Salmon, cream cheese, rice, avocado, nori', 'RU': "Лосось, сливочный сыр, рис, авокадо, нори"},
            price: 910,
            count: 1,
            grams: 200,
            img: "",
          },
          {
            id: 32,
            name:{'EN': 'Seared salmon roll', 'RU': "Ролл с опаленным лососем"} ,
            title:{'EN': 'Salmon, eel, avocado, nori, tobiko, unagi yuzu sauce, sesame, spicy sauce, rice', 'RU': "Лосось, угорь, авокадо, нори, тобико, соус унаги юдзу, кунжут, спайси соус, рис"},
            price: 1020,
            count: 1,
            grams: 200,
            img: "",
          }
    ]
  },  
  {
    'data' : 'snacks',
    'mini' : false,
    'cat':{"EN":'Snacks',"RU":'Закуски'},
    'items': [
        {
            id: 76,
            name:{'EN': 'Meat Plateau', 'RU':"Мясное плато"},
            title:{'EN': 'Prosciutto, roast beef, salami', 'RU':"Прошутто, ростбиф, салями" },
            price: 1299,
            count: 1,
            grams: 150,
            img: "https://avatars.mds.yandex.net/get-eda/3506707/3a4692592f0e4b5a9100d490f02a0974/450x300",
          },
          {
            id: 77,
            name:{'EN': 'Chicken liver pate with brioche', 'RU':"Паштет из куриной печени с бриошью" },
            title:{'EN': 'Chicken liver pate, brioche, fig jam', 'RU':"Паштет из куриной печени, бриошь, джем из инжира" },
            price: 399,
            count: 1,
            grams: 120,
            img: "https://avatars.mds.yandex.net/get-eda/3420935/e586c76c33c445259979def0c227b0fd/450x300",
          },
          {
            id: 78,
            name:{'EN': 'Antipasti Set', 'RU': "Сет Антипасти"},
            title:{'EN': 'Kalamata olives, sun-dried tomatoes, artichokes', 'RU':"Оливки каламата, вяленые томаты, артишоки" },
            price: 1200,
            count: 1,
            grams: 250,
            img: "https://avatars.mds.yandex.net/get-eda/3504598/5f54f90f71ff42eeb2bcf0cd3c58a9cc/450x300",
          },
          {
            id: 79,
            name:{'EN': 'Cheese Plateau', 'RU':"Сырное плато" },
            title:{'EN': 'Gorgonzola, Brie, Parmesan, nuts, dried fruit, grapes and honey', 'RU':"Горгонзола, бри, пармезан, орехи, сухофрукты, виноград и мед" },
            price: 1800,
            count: 1,
            grams: 340,
            img: "https://avatars.mds.yandex.net/get-eda/3454897/71660cfbea344b4fbf02ce26adde63b3/450x300",
          },
          
          {
            id: 's1',
            name:{'EN': 'Hummus with grilled broccoli', 'RU':"Хумус с брокколи гриль"},
            title:{'EN': 'Chickpeas, tahini, ground cumin, lemon juice, broccoli, olive oil, sea salt, slivered almonds, zatar, sesame oil, sunflower and pumpkin seeds, microgreens', 'RU':"Нут, тахини, кумин молотый, лимонный сок, брокколи, масло оливковое, соль морская, миндаль слайс, затар, масло кунжутное, семечка подсолничника и тыквы, микрозелень"},
            price: 490,
            count: 1,
            grams: 270,
            img: "/assets/items/s1.jpeg",
          },
     
    ]
  }, 
  {
    'data' : 'salads',
    'mini' : false,
    'cat':{"EN":'Salads',"RU":'Салаты'},
    'items': [
        {
            id: 41,
            name:{'EN':'Broken cucumber and salmon', 'RU':"Битый огурец и лосось"}, 
            title:{'EN':'Salmon, cucumbers, onions, mixed greens, cashew nuts', 'RU':"Лосось, огурцы, лук репчатый, зелень микс, орех кешью"}, 
            price: 710,
            count: 1,
            grams: 360,
            img: "https://avatars.mds.yandex.net/get-eda/3491582/25e0dfd69b2e4a4a9b73f952b85df7a4/450x300",
          },
          {
            id: 42,
            name:{'EN':'Greek salad with kalamata olives', 'RU':"Греческий салат с оливками каламата"}, 
            title:{'EN':'Baku tomatoes, cucumbers, bell peppers, red onions, mixed salad', 'RU':"Помидоры бакинские, огурцы, болгарский перец, красный лук, микс салатов"},
            price: 610,
            count: 1,
            grams: 310,
            img: "https://avatars.mds.yandex.net/get-eda/3547279/11fb7fac98ba4b90b0e57f9f59a77f26/450x300",
          },
          {
            id: 43,
            name:{'EN':'Green Bowl', 'RU':"Зеленый боул"},
            title:{'EN':'Avocado, cucumber, chicken egg, chuca lettuce, spinach', 'RU':"Авокадо, огурец, яйцо куриное, чука салат, шпинат"}, 
            price: 489,
            count: 1,
            grams: 170,
            img: "https://avatars.mds.yandex.net/get-eda/3805363/38668bf155ad480288bd1359c6493097/450x300",
          },
          {
            id: 44,
            name:{'EN':'Avocado shrimp and tomato salad', 'RU':"Салат с креветками авокадо и томатами"}, 
            title:{'EN':'Shrimp, Baku tomatoes, avocado, cilantro, sour cream, olive oil', 'RU':"Креветки, помидоры бакинские, авокадо, кинза, сметана, оливковое масло"},
            price: 799,
            count: 1,
            grams: 250,
            img: "https://avatars.mds.yandex.net/get-eda/3559865/16e8aaa2c91d4e1d87a1163fee124891/450x300",
          },
          {
            id: 45,
            name:{'EN':'Grilled shrimp Caesar', 'RU':"Цезарь с креветками на гриле"}, 
            title:{'EN':'Romano salad leaves, shrimp, cherry tomatoes, parmesan cheese, caesar sauce, wheat baguette croutons', 'RU':"Листья салата Романо, креветки, помидоры черри, сыр пармезан, соус цезарь, гренки из пшеничного багета"}, 
            price: 610,
            count: 1,
            grams: 250,
            img: "https://avatars.mds.yandex.net/get-eda/3725642/a7d5b0ec3e6b4f209bb066327c3cce68/450x300",
          },
          {
            id: 46,
            name:{'EN':'Caesar with grilled chicken breast', 'RU':"Цезарь с куриной грудкой на гриле"}, 
            title:{'EN':'Romano salad leaves, chicken fillet, cherry tomatoes, parmesan cheese, sauce', 'RU':"Листья салата Романо, куриное филе, помидоры черри, сыр пармезан, соус"},
            price: 510,
            count: 1,
            grams: 250,
            img: "https://avatars.mds.yandex.net/get-eda/3805363/c70b5268269944d4aa2eeccbc8c89f5e/450x300",
          },
          {
            id: 47,
            name:{'EN':'Nisuaz', 'RU':"Нисуаз"}, 
            title:{'EN':'Tuna fillet, baked potatoes, green beans, olives', 'RU':"Филе тунца, картофель запеченный, фасоль стручковая, оливки"}, 
            price: 999,
            count: 1,
            grams: 220,
            img: "",
          },

          {
            id: 'sd1',
            name:{'EN':'Salad with shrimp, avocado and tomatoes', 'RU':"Салат с креветками, авокадо и томатами"}, 
            title:{'EN':'Shrimp, Baku tomatoes, avocado, cilantro, sour cream, olive oil, sesame', 'RU':"Креветки, помидоры бакинские, авокадо, кинза, сметана, оливковое масло, кунжут"}, 
            price: 800,
            count: 1,
            grams: 250,
            img: "/assets/items/sd1.jpeg",
          },
          
          {
            id: 'sd2',
            name:{'EN':'Salad with seafood and beet dressing', 'RU':"Салат с морепродуктами и свекольной заправкой"}, 
            title:{'EN':'Fresh tomatoes, cherry tomatoes, cucumbers, green peas, cilantro, chervil, cream cheese beet, capers on a branch, mini squid, scallop, tiger prawns with head (1 piece), mussels, dressing (garlic juice, olive oil, lemon juice), salt, pepper', 'RU':"Помидоры свежие, томаты черри, огурцы, стручковый горох, кинза, кервель, крем-чиз свекольный, каперсы на ветке, мини-кальмар, гребешок, тигровые креветки с головой (1 шт.), мидии, заправка (чесночный сок, оливковое масло, лимонный фреш), соль, перец"}, 
            price: 1100,
            count: 1,
            grams: 290,
            img: "/assets/items/sd2.jpeg",
          },
          
          {
            id: 'sd3',
            name:{'EN':'Green salad with crab', 'RU':"Зелёный салат с крабом"}, 
            title:{'EN':'Ruccola, cucumber, avocado, crab, sesame dressing, parmesan, cherry tomatoes', 'RU':"Руккола, огурец, авокадо, краб, кунжутный дрессинг, пармезан, помидоры черри"}, 
            price: 850,
            count: 1,
            grams: 240,
            img: "/assets/items/sd3.jpeg",
          },
          {
            id: 'sd1',
            name:{'EN':'Burrata with tomatoes and spinach', 'RU':"Буррата с томатами и шпинатом"}, 
            title:{'EN':'Burrata cheese, tomatoes, spinach', 'RU':"Сыр буррата, томаты, шпинат"}, 
            price: 890,
            count: 1,
            grams: 120,
            img: "",
          }
    ]
  },
  {
    'data' : 'brusshetta',
    'mini' : false,
    'cat':{"EN":'Bruschetta',"RU":'Брускетты'},
    'items': [
        {
            id: 61,
            name:{'EN': 'With Prosciutto and Strachella', 'RU':"С Прошутто и Страчеллой" },
            title:{'EN': 'Grain bread, Prosciutto, Strachella cheese, cherry tomatoes, lettuce', 'RU':"Хлеб зерновой, Прошутто, сыр Страчелла, помидоры Черри, салат" },
            price: 720,
            count: 1,
            grams: 190,
            img: "https://avatars.mds.yandex.net/get-eda/3593277/5753bda1f86e431db636ba66b1bc757c/450x300",
          },
          {
            id: 62,
            name:{'EN': 'Bruschetta with crab and pickled tomatoes', 'RU':"Брускетта с крабом и маринованными томатами" },
            title:{'EN': 'Grain bread, crab, tomatoes, romano salad, spicy sauce', 'RU':"Хлеб зерновой, краб, помидоры, салат романо, спайси соус" } ,
            price: 920,
            count: 1,
            grams: 190,
            img: "https://avatars.mds.yandex.net/get-eda/3502800/f9bcd9e54cff443394f97a19aaaf297b/450x300",
          },
          {
            id: 63,
            name:{'EN': 'With salmon and avocado', 'RU':"С лососем и авокадо" },
            title:{'EN': 'Grain bread, lightly salted salmon, avocado, tomato, creamy', 'RU':"Хлеб зерновой, лосось слабосоленый, авокадо, помидоры, сливочный" },
            price: 720,
            count: 1,
            grams: 220,
            img: "https://avatars.mds.yandex.net/get-eda/3436037/a6696af622ca4bfa972e373ad7ea670d/450x300",
          },
          {
            id: 'b1',
            name: {'EN': "Bruschetta with roast beef and red onions", 'RU': "Брускетта с ростбифом и красным луком"},
            title: {'EN': "Grain bread, roast beef, tomatoes, red onion, mustard, horseradish, olive oil, parsley", 'RU': "Хлеб зерновой, ростбиф (говядина), помидоры, красный лук, горчица, хрен, оливковое масло, петрушка"},
            price: 520,
            count: 1,
            grams: 190,
            img: "/assets/items/b1.jpeg"
          },
          {
            id: 65,
            name:{'EN': 'With tomatoes and avocado', 'RU':"С томатами и авокадо" },
            title:{'EN': 'Grain bread, tomatoes, avocado, guacamole sauce, Romano salads, Frise', 'RU': "Хлеб зерновой, помидоры, авокадо, соус Гуакамоле, салаты Романо, Фризе"},
            price: 520,
            count: 1,
            grams: 165,
            img: "https://avatars.mds.yandex.net/get-eda/3781088/e561170d1c754343833e9f34e786ef37/450x300",
          },
    ]
  },
  {
    'data': 'soap',
    'mini' : false,
    'cat':{"EN":'Soups',"RU":'Супы'},
    'items': [
        {
            id: 'so1',
            name:{'EN': 'Borscht with veal cheek and smoked prunes', 'RU':"Борщ с телячьей щёчкой и копченым черносливом"} ,
            title:{'EN': 'Salt, black pepper, sugar, garlic fraiche, dill, parsley, sour cream, green onions, borodino bread', 'RU':"Соль, перец черный, сахар, фреш чесночный, укроп, петрушка, сметана, лук зеленый, хлеб бородинский"} ,
            price: 490,
            count: 1,
            grams: 450,
            img: "/assets/items/so1.jpeg",
          },
          {
            id: 86,
            name:{'EN': 'Chicken noodle soup', 'RU':"Суп-лапша из цыпленка"} ,
            title:{'EN': 'Chicken broth, vermicelli, chicken fillet, quail egg, herbs', 'RU':"Куриный бульон, вермишель, куриное филе, перепелиное яйцо, зелень"} ,
            price: 399,
            count: 1,
            grams: 450,
            img: "https://avatars.mds.yandex.net/get-eda/3725642/9f060f3824d44083bbdc5dae565dce9f/450x300",
          }, 
          {
            id: 'so2',
            name:{'EN': 'Tom yam with shrimp and wood mushrooms', 'RU':"Том ям с креветками и древесными грибами"} ,
            title:{'EN': 'Squid, wood mushrooms, basmati rice, sesame oil, coconut milk, tomato, lime, shrimp, tomato paste, ginger, oyster mushrooms, mussels, cilantro', 'RU':"Кальмар, грибы древесные, рис басмати, масло кунжутное, молоко кокосовое, помидоры, лайм, креветки, паста томатная, имбирь, вешенки, мидии, кинза"} ,
            price: 750,
            count: 1,
            grams: 580,
            img: "/assets/items/so2.jpeg",
          },
          {
            id: 'so3',
            name:{'EN': 'Salmon, sea bass and cod soup', 'RU':"Уха из лосося, сибаса и трески"} ,
            title:{'EN': 'Fish broth, mussels, salmon, sea bass, cod, potatoes, tomatoes, garlic fresh, dill, parsley', 'RU':"Бульон рыбный, мидии, лосось, сибас, треска, картофель, томаты, чесночный фреш, укроп, петрушка"} ,
            price: 650,
            count: 1,
            grams: 450,
            img: "/assets/items/so3.jpeg",
          },
          {
            id: 'so4',
            name:{'EN': 'Lentil cream soup with artichokes and pickled onions', 'RU':"Крем-суп из чечевицы с артишоками и маринованным лучком"} ,
            title:{'EN': 'Lentils, carrots, onions, potatoes, artichokes, pearl onions, green onions, seeds, ground olives, olive oil, vegetable oil, garlic, salt, pepper', 'RU':"Чечевица, морковь, лук репчатый, картофель, артишоки, лук жемчужный, лук зеленый, семечки, земля из маслин, оливковое масло, масло растительное, чеснок, соль, перец"} ,
            price: 420,
            count: 1,
            grams: 330,
            img: "/assets/items/so4.jpeg",
          },
    ]
  },
  {
    'data' : 'pasta',
    'mini' : false,
    'cat':{"EN": 'Pasta and risotto',"RU": 'Паста и ризотто'},
    'items': [
        {
            id: 'p1',
            name:{'EN':'Spaghetti with crab in tomato sauce', 'RU':"Спагетти с крабом в томатном соусе"}, 
            title:{'EN':'Spaghetti, crab, chicken broth, basil, tomato sauce, butter', 'RU':"Спагетти, краб, куриный бульон, базилик, соус томатный, масло сливочное"}, 
            price: 990,
            count: 1,
            grams: 300,
            img: "/assets/items/p1.jpeg",
          },
          {
            id: 'p2',
            name:{'EN':'Tagliatelle with seafood', 'RU':"Тальятелле с морепродуктами"}, 
            title:{'EN':'Tagliatelle, calamari, shrimp, mussels, octopus, white wine, chicken broth, rosemary, thyme, olive oil, vegetable oil, Parmesan', 'RU':"Тальятелле, кальмары, креветки, мидии, осьминог, вино белое, куриный бульон, розмарин, тимьян, масло оливковое, масло растительное, пармезан"}, 
            price: 990,
            count: 1,
            grams: 390,
            img: "/assets/items/p2.jpeg",
          },   {
            id: 'p3',
            name:{'EN':'Risotto with porcini mushrooms', 'RU':"Ризотто с белыми грибами"}, 
            title:{'EN':'Arborio rice, porcini mushrooms', 'RU':"Рис арборио, белые грибы"}, 
            price: 920,
            count: 1,
            grams: 190,
            img: "/assets/items/p3.jpeg",
          },   {
            id: 'p4',
            name:{'EN':'Penne with beef, porcini mushrooms and truffle sauce', 'RU':"Пенне с говядиной, белыми грибами и трюфельным соусом"}, 
            title:{'EN':'Penne, beef, parmesan cheese, porcini mushrooms, white wine, cream, tomatoes, truffle oil, olive oil', 'RU':"Пенне, говяжья вырезка, сыр пармезан, белые грибы, вино белое, сливки, помидоры, масло трюфельное, масло оливковое"}, 
            price: 920,
            count: 1,
            grams: 350,
            img: "/assets/items/p4.jpeg",
          },        {
            id: 'p7',
            name:{'EN':'Spaghetti with vongole', 'RU':"Спагетти с вонголе"}, 
            title:{'EN':'Vongole, white wine, salt, pepper, shallot, garlic puree, chicken broth, butter, parsley', 'RU':"Вонголе, вино белое, соль, перец, шалот, чесночное пюре, бульон куриный, сливочное масло, петрушка"}, 
            price: 750,
            count: 1,
            grams: 330,
            img: "/assets/items/p7.jpeg",
          },   {
            id: 'p8',
            name:{'EN':'Risotto with beef tartare', 'RU':"Ризотто с тартаром из говядины"}, 
            title:{'EN':'Chicken broth, salt, pepper, butter, cream, beef tartare, green peas, watercress, olive oil, truffle oil', 'RU':"Куриный бульон, соль, перец, масло сливочное, сливки, тартар из говядины, горошек зеленый, кресс-салат, масло оливковое, масло трюфельное"}, 
            price: 790,
            count: 1,
            grams: 190,
            img: "/assets/items/p8.jpeg",
          },   {
            id: 'p9',
            name:{'EN':'Salmon ravioli', 'RU':"Равиоли с лососем"}, 
            title:{'EN':'Salmon, cremette cheese, fish broth, cream, tomatoes, microgreens, spinach, egg yolk, dough', 'RU':"Лосось, сыр креметте, рыбный бульон, сливки, томаты, микрозелень, шпинат, желток, тесто"}, 
            price: 940,
            count: 1,
            grams: 200,
            img: "/assets/items/p9.jpeg",
          },   {
            id: 'p10',
            name:{'EN':'Spaghetti Bolognese', 'RU':"Спагетти Болоньезе"}, 
            title:{'EN':'Spaghetti, bolognese sauce, arabiata pilati sauce, parmesan cheese, olive oil, microgreens, olive ground', 'RU':"Спагетти, соус болоньезе, соус арабьята пилати, сыр пармезан, масло оливковое, микрозелень, земля из маслин"}, 
            price: 790,
            count: 1,
            grams: 250,
            img: "/assets/items/p10.jpeg",
          },
          
    ]
  },  
  {
        'data' : 'noodles',
        'mini' : false,
        'cat':{"EN":'Noodles',"RU":'Лапша'},
        'items': [
          {
            id: 'p5',
            name:{'EN':'Buckwheat noodles with chicken in Asian sauce', 'RU':"Гречневая лапша с курицей в азиатском соусе"}, 
            title:{'EN':'Buckwheat noodles, chicken thigh, bell peppers, carrots, zucchini, pea pods, Singapore sauce, sesame', 'RU':"Лапша гречневая, куриное бедро, болгарский перец, морковь, цукини, стручки гороха, сингапурский соус, кунжут"}, 
            price: 570,
            count: 1,
            grams: 300,
            img: "/assets/items/p5.jpeg",
          }, 
          {
            id: 'p6',
            name:{'EN':'Rice noodles with tiger shrimps', 'RU':"Рисовая лапша с тигровыми креветками"}, 
            title:{'EN':'Rice noodles, tiger shrimp, bell peppers, carrots, zucchini, egg, Singapore sauce, cilantro', 'RU':"Рисовая лапша, тигровые креветки, болгарский перец, морковь, цукини, яйцо, сингапурский соус, кинза"}, 
            price: 670,
            count: 1,
            grams: 320,
            img: "/assets/items/p6.jpeg",
          },
        ]
  },
  {
    'data' : 'fishSeafood',
    'mini' : false,
    'cat':{"EN":'Fish and seafood',"RU":'Рыба и морепродукты'},
    'items': [
        {
          id: 125,
          name:{'EN': 'Salmon steak with vegetable salsa', 'RU':"Стейк лосося с овощной сальсой"},
          title:{'EN': 'Salmon fillet, tomato salsa, avocado, cucumber vegetable oil', 'RU':"Филе лосося, сальса из томатов, авокадо, огурец масло растительное"},
          modifier:{'EN':['on the grill', 'steamed'], 'RU':['на гриле','на пару']},
          price: 1200,
          count: 1,
          grams: 200,
          img: "https://avatars.mds.yandex.net/get-eda/3514991/e93a9c2fb26d46e9bfc020cead3f934e/450x300",
        },
        {
          id: 81,
          name:{'EN': 'Mussels in wine sauce', 'RU':"Мидии в винном соусе"} ,
          title:{'EN': 'Mussels, chicken broth, wine, coconut milk, rosemary, thyme, cilantro', 'RU':"Мидии, куриный бульон, вино, кокосовое молоко, розмарин, тимьян, кинза"},
          price: 720,
          count: 1,
          grams: 500,
          img: "https://avatars.mds.yandex.net/get-eda/3593277/88a00787ad4647a1a789d184cd12667a/450x300",
        },
        {
            id: 80,
            name:{'EN': 'Grilled shrimp with spicy sauce', 'RU':"Креветки на гриле с соусом спайси"} ,
            title:{'EN': 'Shrimp, soy sauce, sesame oil, spicy sauce, sesame seeds, bamboo leaf', 'RU':"Креветки, соевый соус, масло кунжутное, спайси соус, кунжут, лист бамбука"},
            price: 800,
            count: 1,
            grams: 150,
            img: "https://avatars.mds.yandex.net/get-eda/3583740/eb737a5203734f5e8ec1557bf2c8ef49/450x300",
        },  
          
         {
          id: 2342,
          name: {'EN': 'Sea bass fillet with red couscous', 'RU': 'Филе сибаса с красным кускусом'},
          title: {'EN': 'Sea bass fillet, zucchini, cilantro, pesto sauce, olive oil, tomato', 'RU': 'Сибас филе, цукини, кинза, соус песто, масло оливковое, томат'},
          price: 910,
          count: 1,
          grams: 300,
          img: "/assets/items/2342.jpg"
         },  
         {
          id: 2343,
          name: {'EN': 'Black cod on a bed of spinach', 'RU': 'Черная треска на подушке из шпината'},
          title: {'EN': 'Baked black cod fillet served on a bed of poached spinach surrounded by walnut sauce and almond slices', 'RU': 'Запеченное филе черной трески подается на подушке из припущенного шпината в окружении орехового соуса и слайсов миндаля'},
          price: 890,
          count: 1,
          grams: 180,
          img: "/assets/items/2343.jpg"
         },
         {
          id: 'f1',
          name: {'EN': 'Sautéed seafood', 'RU': 'Соте из морепродуктов'},
          title: {'EN': 'Langoustines, shrimp, mussels, squid, scallop, grilled lemon and lime', 'RU': 'Лангустины, креветки, мидии, кальмары, гребешок, лимон и лайм гриль'},
          price: 2400,
          count: 1,
          grams: 550,
          img: "/assets/items/f1.jpeg"
         },
         {
          id: 'f2',
          name: {'EN': 'Mussels in Tom Yum Sauce', 'RU': 'Мидии в соусе том ям'},
          title: {'EN': 'Mussels, shallots, garlic fraiche, coconut milk, tom yum paste, butter, cilantro, bread', 'RU': 'Мидии, лук-шалот, чесночный фреш, молоко кокосовое, паста том ям, сливочное масло, кинза, хлеб'},
          price: 805,
          count: 1,
          grams: 350,
          img: "/assets/items/f2.jpeg"
         }
    ]
  }, 
  {
    'data': 'meatPoultry',
    'mini': false,
    'cat':{"EN":'Meat and poultry',"RU":'Мясо и птица'},
    'items': [
        {
            id: 71,
            name:{'EN': 'Asian beef with rice', 'RU':"Говядина по-азиатски с рисом" },
            title:{'EN': 'Beef loin, rice, pea pods, soy sprouts, Asian sauce', 'RU':"Говяжья вырезка, рис, стручки гороха, ростки сои, соус азиатский" },
            price: 910,
            count: 1,
            grams: 280,
            img: "https://avatars.mds.yandex.net/get-eda/3377781/0ef9d244a4de42268242ae341246337e/450x300",
          },
          {
            id: 72,
            name:{'EN': 'Chicken curry with rice', 'RU':"Курица карри с рисом" },
            title:{'EN': 'Chicken fillet, rice, curry sauce', 'RU':"Куриное филе, рис, карри соус" },
            price: 710,
            count: 1,
            grams: 280,
            img: "https://avatars.mds.yandex.net/get-eda/2415806/5369455898bc4c4d869b3e4eb81f4f5d/450x300",
          },
          {
            id: 73,
            name:{'EN': 'Ribeye steak with grilled corn', 'RU':"Рибай стейк с кукурузой на гриле" },
            title:{'EN': 'Beef loin, corn cob', 'RU':"Говяжья вырезка, початок кукурузы" },
            price: 2600,
            count: 1,
            grams: 380,
            img: "",
          },
          {
            id: 75,
            name:{'EN': 'Grilled filet mignon with zucchini', 'RU':"Филе миньон с цукини на гриле" },
            title:{'EN': 'Beef loin, zucchini, mushroom sauce, vegetable oil', 'RU':"Говяжья вырезка, цукини, грибной соус, масло растительное" },
            price: 1700,
            count: 1,
            grams: 350,
            img: "",
          },
          {
            id: 'm1',
            name:{'EN': 'Chicken with truffle cole sloe', 'RU':"Цыпленок с трюфельным коул слоу" },
            title:{'EN': 'Juicy baked farm chicken served whole with truffle cole sloe', 'RU':"Сочный запечённый фермерский цыпленок подается целиком с трюфельным коул слоу" },
            price: 910,
            count: 1,
            grams: 260,
            img: "/assets/items/m1.jpeg",
          },
          {
            id: 'm2',
            name:{'EN': 'Stewed veal cheek with mashed potatoes and tomatoes', 'RU':"Томлённая телячья щёчка с пюре и томатами" },
            title:{'EN': 'Mashed potatoes, demi-glace sauce, Uzbek tomatoes, cilantro, wine, thyme, garlic, onions, carrots, salt', 'RU':"Пюре картофельное, соус демиглас, помидоры узбекские, кинза, вино, тимьян, чеснок, лук, морковь, соль" },
            price: 890,
            count: 1,
            grams: 340,
            img: "/assets/items/m2.jpeg",
          },
          {
            id: 'm3',
            name:{'EN': 'Beef Stroganoff', 'RU':"Бефстроганов" },
            title:{'EN': 'Beef, cream, mushrooms, walnut sauce, pickles, watercress, almond slices', 'RU':"Говядина, сливки, шампиньоны, соус ореховый, огурцы маринованные, кресс-салат, слайсы миндаля" },
            price: 850,
            count: 1,
            grams: 340,
            img: "",
          },
        
         
    ]
  }, 
  {
    'data' : 'sideDishes',
    'mini' : true,
    'cat':{"EN":'Side dishes',"RU":'Гарниры'},
    'items': [
        {
            id: 66,
            name:{'EN': 'Fried potatoes with oyster mushrooms', 'RU':"Жареный картофель с вешенками" },
            title:{'EN': 'Potatoes, oyster mushrooms, onions, parsley, garlic oil, salt, pepper', 'RU':"Картофель, грибы вешенки, лук, петрушка, чесночное масло, соль, перец" },
            price: 410,
            count: 1,
            grams: 200,
            img: "",
          },
          {
            id: 67,
            name:{'EN': 'Roasted spinach with tomatoes', 'RU':"Жареный шпинат с томатами" },
            title:{'EN': 'Spinach, garlic oil, cherry tomatoes, salt, pepper', 'RU': "Шпинат, чесночное масло, томаты черри, соль, перец"},
            price: 410,
            count: 1,
            grams: 90,
            img: "",
          },
          {
            id: 68,
            name:{'EN': 'Mashed potatoes', 'RU':"Картофельное пюре" },
            title:{'EN': 'Potatoes, butter, cream', 'RU':"Картофель, сливочное масло, сливки" },
            price: 360,
            count: 1,
            grams: 150,
            img: "",
          },
          {
            id: 69,
            name:{'EN': 'Grilled corn', 'RU':"Кукуруза на гриле" },
            title:{'EN': 'Corn', 'RU':"Кукуруза" },
            price: 410,
            count: 1,
            grams: 200,
            img: "",
          },
          {
            id: 70,
            name:{'EN': 'Asparagus', 'RU':"Спаржа" },
            title:{'EN': 'Asparagus, olive oil', 'RU':"Спаржа, оливковое масло" },
            price: 510,
            count: 1,
            grams: 100,
            img: "",
          },
          {
            id: 'v1',
            name:{'EN': 'Cabbage steak with red caviar', 'RU':"Стейк из капусты с красной икрой" },
            title:{'EN': 'Grilled cabbage steak served with cream sauce and red caviar', 'RU':"Стейк из капусты на гриле подается со сливочным соусом и красной икрой" },
            price: 690,
            count: 1,
            grams: 170,
            img: "/assets/items/v1.jpeg",
          },
          {
            id: 'v2',
            name:{'EN': 'Baked yams with mushrooms and zazaki sauce', 'RU':"Запеченный батат с грибами и соусом дзадзики" },
            title:{'EN': 'Batat, mushrooms, oyster mushrooms, ceps, vegetable oil, garlic puree, cucumbers, lean sour cream, olive oil, truffle oil, pearl onions, green onions, ground olives, dill, salt, pepper, thyme', 'RU':"Батат, шампиньоны, вешенки, белые грибы, масло растительное, чесночное пюре, огурцы, постная сметана, масло оливковое, масло трюфельное, жемчужный лук, лук зеленый, земля из маслин, укроп, соль, перец, тимьян" },
            price: 590,
            count: 1,
            grams: 270,
            img: "/assets/items/v2.jpeg",
          },
    ]
  }, 
  {
    'data' : 'desserts',
    'mini' : false,
    'cat': {"EN": 'Desserts', "RU": 'Десерты'},
    'items': [
        {
            id: 89,
            name:{'EN': 'Warm apple pie with an ice cream scoop', 'RU':"Теплый яблочный пирог с шариком мороженого"} ,
            title:{'EN': 'Homemade apple and puff pastry pie, ice cream scoop, nuts', 'RU':"Домашний пирог из яблок и слоеного теста, шарик мороженого, орехи"} ,
            price: 520,
            count: 1,
            grams: 210,
            img: "",
          },
          {
            id: 'ds2',
            name:{'EN': 'Miles with patisserie cream and fresh berries', 'RU':"Милей с кремом патисьер и свежими ягодами"},
            title:{'EN': 'Puff pastry, cream, raspberries, strawberries, blueberries, blackberries, freeze-dried raspberries', 'RU':"Тесто слоеное, крем, малина, клубника, голубика, ежевика, малина сублимированная"},
            price: 750,
            count: 1,
            grams: 160,
            img: "/assets/items/ds2.jpeg",
          },
         
    ]
  },
  {
        'data' : 'children',
        'mini' : false,
        'cat':{"EN":'Children`s menu',"RU":'Детское меню'},
        'items': [
            {
                id: 55,
                name:{'EN': 'Beef stroganoff with mashed potatoes', 'RU':"Бефстроганов из говядины с картофельным пюре" },
                title:{'EN': 'Beef loin, mashed potatoes, cream sauce', 'RU':"Говяжья вырезка, картофельное пюре, сливочный соус" },
                price: 499,
                count: 1,
                grams: 240,
                img: "https://avatars.mds.yandex.net/get-eda/3774488/730b6bce9f584119a276fb9f20422bf6/450x300",
              },
              {
                id: 56,
                name:{'EN': 'Chicken cutlets with mashed potatoes', 'RU':"Куриные котлеты с картофельным пюре" },
                title:{'EN': 'Minced chicken, mashed potatoes, butter', 'RU':"Куриный фарш, картофельное пюре, сливочное масло" },
                price: 499,
                count: 1,
                grams: 240,
                img: "https://avatars.mds.yandex.net/get-eda/3559865/d81289567aa14454863b5cbe69461918/450x300",
              },
              {
                id: 57,
                name:{'EN': 'Chicken broth with noodles and vegetables', 'RU':"Куриный бульон с лапшой и овощами" },
                title:{'EN': 'Chicken broth, chicken filet, noodles, vegetables', 'RU':"Куриный бульон, куриное филе, лапша, овощи" },
                price: 229,
                count: 1,
                grams: 230,
                img: "https://avatars.mds.yandex.net/get-eda/3436037/93fce62acc254aee95de5b1827dea56a/450x300",
              },
              {
                id: 58,
                name:{'EN': 'Minestrone', 'RU':"Минестроне" },
                title:{'EN': 'Vegetable broth, vegetables', 'RU':"Овощной бульон, овощи" },
                modifier: {
                  "EN": [
                    'standard',
                    'With chicken meatballs'
                  ],
                  "RU": [
                    'cтандартное',
                    'c куриными фрикадельками'
                  ]
                },
                price: 229,
                count: 1,
                grams: 240,
                img: "https://avatars.mds.yandex.net/get-eda/3724421/4128d6509dbe49faa7f43205d81a0557/450x300",
              },
              
              {
                id: 59,
                name:{'EN': 'Penne in cream sauce with parmesan cheese', 'RU':"Пенне в сливочном соусе с сыром пармезан" },
                title:{'EN': 'Penne, parmesan cheese, cream sauce', 'RU':"Пенне, сыр пармезан, сливочный соус" },
                price: 359,
                count: 1,
                grams: 210,
                img: "https://avatars.mds.yandex.net/get-eda/3813301/900e522b23a84369b9cd6a96527b6d48/450x300",
              },
             
        ]
  },   
 
];






module.exports = { items };