
const items = [
  {
    'data' : 'season',
    'mini' : false,
    'cat':{"EN":'Seasonal offer',"RU":'Сезонное предложение'},
    'items': [
      {
        id: 'ip1',
        name:{'EN': "Okroshka with kvass", 'RU':"Окрошка на квасе"} ,
        title:{'EN': '', 'RU':""},
        price: 650,
        count: 1,
        grams: 420,
        img: "https://eda.yandex/images/15305317/d9df730e0f7b41199e8da3ce7b718ffb-400x400nocrop.jpeg",
      },
      {
        id: 'ip2',
        name:{'EN': "Summer salad with trout", 'RU':"Летний салат с форелью"} ,
        title:{'EN': '', 'RU':""},
        price: 750,
        count: 1,
        grams: 180,
        img: "https://eda.yandex/images/15252145/7942fc6a7d9748de9f8b05a2c9b00a47-400x400nocrop.jpeg",
      },
      {
        id: 'ip3',
        name:{'EN': "Gazpacho with stracciatella cheese", 'RU':"Гаспачо с сыром страчателла"} ,
        title:{'EN': '', 'RU':""},
        price: 800,
        count: 1,
        grams: 340,
        img: "https://eda.yandex/images/15252145/091eb4a5284c4082acb5203ffb14492a-400x400nocrop.jpeg",
      },
      {
        id: 'ip9',
        name:{'EN': "Okroshka with kefir", 'RU':"Окрошка на кефире"} ,
        title:{'EN': '', 'RU':""},
        price: 650,
        count: 1,
        grams: 420,
        img: "https://eda.yandex/images/15305317/d9df730e0f7b41199e8da3ce7b718ffb-400x400nocrop.jpeg",
      },
      {
        id: 'ip4',
        name:{'EN': "Green salad with lemon dressing", 'RU':"Зеленый салат с лимонной заправкой"} ,
        title:{'EN': '', 'RU':""},
        price: 670,
        count: 1,
        grams: 170,
        img: "https://eda.yandex/images/15382203/b6af0e232923478a9b6c32d831f2cb1c-400x400nocrop.jpeg",
      },
      {
        id: 'ip5',
        name:{'EN': "Village Salad", 'RU':"Салат Деревенский"} ,
        title:{'EN': '', 'RU':""},
        price: 550,
        count: 1,
        grams: 225,
        img: "https://eda.yandex/images/15252145/1e4c2901b1734b4098b4b72fed9413c4-400x400nocrop.jpeg",
      },
      {
        id: 'ip6',
        name:{'EN': "Juicy Watermelon with Feta Cheese", 'RU':"Сочный Арбуз с сыром Фета"} ,
        title:{'EN': '', 'RU':""},
        price: 500,
        count: 1,
        grams: 160,
        img: "",
      },
      {
        id: 'ip7',
        name:{'EN': "Eggplant Arabyata", 'RU':"Баклажан Арабьята"} ,
        title:{'EN': '', 'RU':""},
        price: 900,
        count: 1,
        grams: 330,
        img: "https://eda.yandex/images/15377433/6f8e9b6b30c7424fa5c9117555da9b9e-450x300.jpeg",
      },
      {
        id: 'ip8',
        name:{'EN': "Panna Cotta", 'RU':"Панна-Котта"} ,
        title:{'EN': '', 'RU':""},
        price: 660,
        count: 1,
        grams: 100,
        img: "",
      },
      {
        id: 'ip10',
        name:{'EN': "Ramiro Peppers", 'RU':"Перцы Рамиро"} ,
        title:{'EN': '', 'RU':""},
        price: 750,
        count: 1,
        grams: 210,
        img: "/img/assets/season/1.jpg",
      },
      {
        id: 'ip11',
        name:{'EN': "Salad with wild garlic", 'RU':"Салат с черемшой"} ,
        title:{'EN': '', 'RU':""},
        price: 870,
        count: 1,
        grams: 200,
        img: "/img/assets/season/2.jpg",
      },
      ]
  },
  
  {
    'data' : 'breakfast',
    'mini' : false,
    'cat':{"EN":'Breakfasts until 14:00',"RU":'Завтраки до 14:00'}, 
    'items': [
      
          {
            id: 15,
            name:{'EN': 'Zucchini dredges with salmon and cream sauce', 'RU':"Драники из цукини с лососем и сметаной"} ,
            title:{'EN': 'Zucchini, egg, lightly salted salmon, cream sauce', 'RU':"Цукини, яйцо, лосось слабосоленый, соус сметанный"},
            price: 910,
            count: 1,
            grams: 200,
            img: "/assets/img/brekfast/10.jpg",
          },
        {
          id: "breakfast0108202401",
          name:{'EN': 'Casserole with Patissiere cream and fresh berries', 'RU':"Запеканка с кремом Патисьер и свежими ягодами"} ,
          title:{'EN': '', 'RU':""},
          price: 870,
          count: 1,
          grams: 220,
          img: "/assets/img/brekfast/2.jpg",
        },

          {
            id: 16,
            name:{'EN': 'Scramble with mortadella', 'RU':"Скрэмбл с мортаделлой"},
            title:{'EN': '', 'RU':""},
            price: 770,
            count: 1,
            grams: 265,
            img: "/assets/img/brekfast/6.jpg",
          },

          {
            id: 'z1',
            name:{'EN': 'Rice porridge with coconut milk and fresh berries', 'RU':"Рисовая каша на кокосовом молоке со свежими ягодами"},
            title:{'EN': 'Rice, milk, coconut milk, sugar, salt, vanilla sugar, cream, cherry topping, raspberries, blackberries, strawberries, blueberries', 'RU':"Рис, молоко, молоко кокосовое, сахар, соль, ванильный сахар, сливки, топпинг вишневый, малина, ежевика, клубника, голубика"},
            price: 540,
            count: 1,
            grams: 260,
            img: "https://eda.yandex/images/3809330/9fb26f19fac54e71ac15d9f90f739148-450x300.jpeg",
          },
          {
            id: 'z2',
            name:{'EN': 'Buckwheat porridge with poached egg and parmesan', 'RU':"Гречневая каша с яйцом пашот и пармезаном"},
            title:{'EN': 'Buckwheat, fried onions, butter, soy sauce, grana cheese, green onions, pâté, truffle paste, truffle hollandaise, microgreens, olive ground, truffle oil', 'RU':"Гречка, лук жареный, масло сливочное, соевый соус, грана сыр, лук зеленый, пашот, паста трюфельная, голландез трюфельный, микрозелень, земля из маслин, масло трюфельное"},
            price: 550,
            count: 1,
            grams: 370,
            img: "/assets/img/brekfast/8.jpg",
          },{
            id: 'z3',
            name:{'EN': 'Omelet with crab and truffle sauce', 'RU':"Омлет с крабом и трюфельным соусом"},
            title:{'EN': 'Egg, cream, salt, pepper, corn, grana cheese, truffle oil, crab, green onions, truffle sauce', 'RU':"Яйцо, сливки, соль, перец, корн, сыр грана, масло трюфельное, краб, зеленый лук, трюфельный соус"},
            price: 990,
            count: 1,
            grams: 220,
          img: "/assets/img/brekfast/7.jpg",
          },
         
          {
            id: 22,
            name:{'EN': 'Cheesecakes with melted milk and sour cream', 'RU':"Сырники из топленого молока со сметаной"} ,
            title:{'EN': 'Cottage cheese, flour, chicken egg, sour cream', 'RU':"Творог, мука, яйцо куриное, сметана"} ,
            price: 420,
            count: 1,
            grams: 170,
            img: "/assets/img/brekfast/1.jpg",
          },
          {
            id: "breakfast0108202403",
            name:{'EN': 'Benedict with salmon and truffle Golandaise', 'RU':"Бенедикт с лососем и трюфельным Голандез"} ,
            title:{'EN': '', 'RU':""} ,
            price: 990,
            count: 1,
            grams: 220,
            img: "/assets/img/brekfast/4.jpg",
          },

      {
        id: "breakfast0108202402",
        name:{'EN': 'Benedict with mortadella and truffle Golandaise', 'RU':"Бенедикт с мортаделлой с трюфельным Голандез"} ,
        title:{'EN': '', 'RU':""} ,
        price: 990,
        count: 1,
        grams: 220,
        img: "/assets/img/brekfast/9.jpg",
      },


    ]
  },
  
  {
    'data' : 'rawbar',
    'mini' : false,
    'cat' : {"EN":'RAW BAR',"RU":'RAW BAR'},
    'items': [
        {
            id: 48,
            name:{'EN':'Sea urchin', 'RU':"Морской ёж"}, 
            title:{'EN':'Sea urchin, quail egg yolk, Ponzu sauce(1pc.)', 'RU':"Морской ёж, желток перепелиного яйца, соус Понзу(1шт.)"}, 
            price: 440,
            count: 1,
            grams: 10,
            img: "https://avatars.mds.yandex.net/get-eda/3805363/82fc446f3def42d7bdf6a79840d52018/450x300",
          },
         
      {
        id: 'os1',
        name: {
          'EN': 'Sea bass ceviche\n',
          'RU': 'Севиче из сибаса'
        },
        price: 800,
        count: 1,
        grams: 170,
        img: "https://avatars.mds.yandex.net/get-eda/3772831/c5c3a26c9f9b4190b693d9b61960c78f/orig",
      },
      {
        id: 'os4',
        name: {
          'EN': 'Beef carpaccio with truffle',
          'RU': 'Карпаччо из говядины с трюфелем'
        },
        price: 950,
        count: 1,
        grams: 170,
        img: "https://eda.yandex/images/3806315/f6b83d6aa2784cf4a1fc582d28a0fc9b-650x500.jpeg",
      },
          {
            id: 50,
            name:{'EN':'Salmon and avocado tartare', 'RU':"Тартар из лосося и авокадо"}, 
            title:{'EN':'Salmon fillet, avocado, sesame, olive oil, ponzu sauce, strawberries', 'RU':"Филе лосося, авокадо, кунжут, оливковое масло, соус понзу, клубника"},
            price: 980,
            count: 1,
            grams: 190,
            img: "https://eda.yandex/images/13439948/e81bce53f2b84f3b8c9eb2ef2d158cdb-450x300.jpeg",
          },
          {
            id: 51,
            name:{'EN':'Tuna tartar', 'RU':"Тартар из тунца"}, 
            title:{'EN':'Tuna fillet, avocado, guacamole, sesame oil, soy sauce', 'RU':"Филе тунца, авокадо, гуакамоле, кунжутное масло, соевый соус"}, 
            price: 800,
            count: 1,
            grams: 200,
            img: "https://eda.yandex/images/2761069/079a850a4714436dac0569e109700c73-450x300.jpeg",
          },
          {
            id: 'rwb1',
            name:{'EN':'Beef tartare', 'RU':"Тартар из говядины"}, 
            title:{'EN':'Beef loin, capers, mustard, tabasco, olive oil, croutons', 'RU':"Говяжья вырезка, каперсы, горчица, табаско, оливковое масло, гренки"}, 
            price: 1080,
            count: 1,
            grams: 160,
            img: "https://eda.yandex/images/13912834/ab515a801156455b8f6df5e43929e9a0-450x300.jpeg",
          },
    ]
  },
  {
    'data': 'susi',
    'mini': false,
    'cat':{"EN":'Sushi',"RU":'Суши'},
    items: [
        {
          id: 1,
          name:{'EN': 'Sashimi Shrimp', 'RU': 'Сашими креветка'},
          title: {'EN': 'Shrimp, wasabi, ginger', 'RU':"Креветка, васаби, имбирь"},
          price: 780,
          count: 1,
          grams: 60,
          img: "/assets/items/Sashimishrimp.jpeg",
        },
        {
          id: 2,
          name:{'EN': 'Salmon Sashimi', 'RU': "Сашими лосось"},
          title:{'EN': 'Salmon, wasabi, ginger', 'RU': "Лосось, васаби, имбирь"},
          price: 920,
          count: 1,
          grams: 60,
          img: "/assets/items/Salmonsashimi.jpeg",
        },
        {
          id: 3,
          name:{'EN': 'Tuna Sashimi', 'RU': "Сашими тунец"},
          title:{'EN': 'Tuna, wasabi, ginger', 'RU': "Тунец, васаби, имбирь"},
          price: 920,
          count: 1,
          grams: 60,
          img: "/assets/img/tunaSashimi.jpeg",
        },
        {
          id: 4,
          name:{'EN': 'Sashimi eel', 'RU': "Сашими угорь"},
          price: 1150,
          count: 1,
          grams: 60,
          img: "/assets/img/sashimieel.jpeg",
        },
        {
          id: 5,
          name:{'EN': 'Spicy crab', 'RU': "Спайси с крабом"},
          title:{'EN': 'Crab, rice, nori, spicy sauce', 'RU': "Краб, рис, нори, спайси соус"},
          price: 390,
          count: 1,
          grams: 35,
          img: "/assets/img/spicycrab.jpeg",
        },
        {
          id: 6,
          name:{'EN': 'Spicy shrimp', 'RU': "Спайси с креветкой"},
          title:{'EN': 'Shrimp, rice, nori, spicy sauce', 'RU': "Креветка, рис, нори, спайси соус"},
          price: 240,
          count: 1,
          grams: 35,
          img: "/assets/img/spicyshrimp.jpeg",
        },
        {
          id: 7,
          name:{'EN': 'Spicy salmon', 'RU': "Спайси с лососем"},
          title:{'EN': 'Salmon, rice, nori, spicy sauce', 'RU': "Лосось, рис, нори, спайси соус"},
          price: 330,
          count: 1,
          grams: 35,
          img: "/assets/img/spicysalmon.jpeg",
        },
        {
          id: 8,
          name:{'EN': 'Spicy tuna', 'RU': "Спайси с тунцом"},
          title:{'EN': 'Tuna, rice, nori, spicy sauce', 'RU': "Тунец, рис, нори, спайси соус"},
          price: 310,
          count: 1,
          grams: 35,
          img: "https://eda.yandex/images/3512182/952cd6ccd2464ceb8c9c28c538ea3ebf-450x300.jpeg",
        },
        {
          id: 9,
          name:{'EN': 'Spicy with eels', 'RU': "Спайси с угрем"},
          title:{'EN': 'Eel, rice, nori, spicy sauce', 'RU': "Угорь, рис, нори, спайси соус"},
          price: 380,
          count: 1,
          grams: 35,
          img: "/assets/img/spicywitheels.jpeg",
        },
        {
          id: 10,
          name:{'EN': 'Sushi with shrimp', 'RU': "Суши с креветкой"},
          title:{'EN': 'Shrimp, rice', 'RU': "Креветка, рис"},
          price: 210,
          count: 1,
          grams: 30,
          img: "/assets/items/Sushishrimp.jpeg",
        },
        {
          id: 11,
          name:{'EN': 'Sushi with salmon', 'RU': "Суши с лососем"},
          title:{'EN': 'Salmon, rice', 'RU': "Лосось, рис"},
          price: 310,
          count: 1,
          grams: 30,
          img: "/assets/img/sushiwithsalmon.jpeg",
        },
        {
          id: 12,
          name:{'EN': 'Sushi with tuna', 'RU': "Суши с тунцом"},
          title:{'EN': 'Tuna, rice', 'RU': "Тунец, рис"},
          price: 270,
          count: 1,
          grams: 30,
          img: "/assets/img/susiTuna.jpg",
        },
        {
          id: 13,
          name:{'EN': 'Sushi with eel', 'RU': "Суши с угрем"},
          title:{'EN': 'Eel, rice', 'RU': "Угорь, рис"},
          price: 450,
          count: 1,
          grams: 30,
          img: "/assets/img/sushiwitheel.jpeg",
        },
      ]
  },
  {
    'data' : 'roll',
    'mini' : false,
    'cat':{"EN":'Rolls',"RU":'Роллы'},
    'items': [
        {
            id: 24,
            name: {'EN': 'Maki and avocado', 'RU': "Маки с авокадо"},
            title:{'EN': 'Avocado, rice, nori', 'RU': "Авокадо, рис, нори"},
            price: 310,
            count: 1,
            grams: 100,
            img: "/assets/items/Avocadamaki.jpeg",
          },
          {
            id: 25,
            name:{'EN': 'Maki with salmon', 'RU': "Маки с лососем"},
            title:{'EN': 'Salmon, rice, nori', 'RU': "Лосось, рис, нори"},
            price: 670,
            count: 1,
            grams: 100,
            img: "/assets/img/makiwithsalmon.jpeg",
          },
          {
            id: 26,
            name:{'EN': 'Poppies with cucumber', 'RU': "Маки с огурцом"},
            title:{'EN': 'Cucumber, rice, nori', 'RU': "Огурец, рис, нори"},
            price: 260,
            count: 1,
            grams: 100,
            img: "/assets/items/Makicucumber.jpeg",
          },
          {
            id: 27,
            name:{'EN': 'Tuna maki', 'RU': "Маки с тунцом"} ,
            title:{'EN': 'Tuna, rice, nori', 'RU': "Тунец, рис, нори"} ,
            price: 410,
            count: 1,
            grams: 100,
            img: "https://eda.yandex/images/3583740/4b7ea510c4a54018af14cb0119a49948-450x300.jpeg",
          },
          {
            id: 28,
            name:{'EN': 'Poppies with eel', 'RU': "Маки с угрем"},
            title:{'EN': 'Eel, rice, nori', 'RU': "Угорь, рис, нори"},
            price: 800,
            count: 1,
            grams: 100,
            img: "/assets/img/poppieswitheel.jpeg",
          },
          {
            id: 29,
            name:{'EN': 'California Roll', 'RU': "Ролл Калифорния"} ,
            title:{'EN': 'Crab, rice, Japanese mayonnaise, avocado, nori, tobiko', 'RU': "Краб, рис, японский майонез, авокадо, нори, тобико"},
            price: 1080,
            count: 1,
            grams: 190,
            img: "/assets/items/RollCalifornia.jpeg",
          },
          {
            id: 30,
            name:{'EN': 'Roll Canada', 'RU': "Ролл Канада"} ,
            title:{'EN': 'Salmon, eel, cream cheese, avocado, nori, unagi yuzu sauce, sesame, rice', 'RU': "Лосось, угорь, сливочный сыр, авокадо, нори, соус унаги юдзу, кунжут, рис"},
            price: 1300,
            count: 1,
            grams: 200,
            img: "https://eda.yandex/images/3538649/4e94d9ae011b451293ef4a9b569530d4-450x300.jpeg",
          },
          {
            id: 31,
            name:{'EN': 'Philadelphia Roll', 'RU': "Ролл Филадельфия"},
            title:{'EN': 'Salmon, cream cheese, rice, avocado, nori', 'RU': "Лосось, сливочный сыр, рис, авокадо, нори"},
            price: 1250,
            count: 1,
            grams: 200,
            img: "https://eda.yandex/images/13912834/505bfe0e0a574f3f90d40ffff9867b3b-450x300.jpeg",
          },
          {
            id: 32,
            name:{'EN': 'Seared salmon roll', 'RU': "Ролл с опаленным лососем"} ,
            title:{'EN': 'Salmon, eel, avocado, nori, tobiko, unagi yuzu sauce, sesame, spicy sauce, rice', 'RU': "Лосось, угорь, авокадо, нори, тобико, соус унаги юдзу, кунжут, спайси соус, рис"},
            price: 1300,
            count: 1,
            grams: 200,
            img: "/assets/items/Rollwithsearedsalmon.jpeg",
          }
    ]
  },  
  {
    'data' : 'starters',
    'mini' : false,
    'cat':{"EN":'Starters',"RU":'Закуски'},
    'items': [
        {
          id: 76,
          name:{'EN': 'Cucumber and eel', 'RU':"Огурец и угорь"},
          title:{'EN': '', 'RU':"" },
          price: 700,
          count: 1,
          grams: 170,
          img: "",
        },
      {
        id: 76214654,
        name:{'EN': 'Baked Camembert', 'RU':"Запечённый камамбер"},
        title:{'EN': '', 'RU':"" },
        price: 1200,
        count: 1,
        grams: 225,
        img: "https://eda.yandex/images/13058477/e005011873fa46cf9214a8c35c1ad0fd-400x400nocrop.jpeg",
      },
      {
        id: 762146254,
        name:{'EN': 'Pike caviar with toasts', 'RU':"Икра щуки с тостами"},
        title:{'EN': '', 'RU':"" },
        price: 980,
        count: 1,
        grams: 130,
        img: "https://eda.yandex/images/3191933/e760f8aa043b4f0ba57827f2517af82d-400x400nocrop.jpeg",
      },
        {
            id: 76,
            name:{'EN': 'Meat Plateau', 'RU':"Мясное плато"},
            title:{'EN': 'Prosciutto, roast beef, salami', 'RU':"Прошутто, ростбиф, салями" },
            price: 1600,
            count: 1,
            grams: 150,
            img: "/assets/img/assorti.jpg",
          },
          {
            id: 77,
            name:{'EN': 'Chicken liver pate with brioche', 'RU':"Паштет из куриной печени с бриошью" },
            title:{'EN': 'Chicken liver pate, brioche, fig jam', 'RU':"Паштет из куриной печени, бриошь, джем из инжира" },
            price: 690,
            count: 1,
            grams: 120,
            img: "https://eda.yandex/images/2761069/438f99bd697e4a6e8755d5aced1f0058-450x300.jpeg",
          },
          {
            id: 78,
            name:{'EN': 'Antipasti Set', 'RU': "Сет Антипасти"},
            title:{'EN': 'Kalamata olives, sun-dried tomatoes, artichokes', 'RU':"Оливки каламата, вяленые томаты, артишоки" },
            price: 1450,
            count: 1,
            grams: 250,
            img: "/assets/img/anitipast.jpg",
          },
          {
            id: 79,
            name:{'EN': 'Cheese Plateau', 'RU':"Сырное плато" },
            title:{'EN': 'Gorgonzola, Brie, Parmesan, nuts, dried fruit, grapes and honey', 'RU':"Горгонзола, бри, пармезан, орехи, сухофрукты, виноград и мед" },
            price: 1800,
            count: 1,
            grams: 340,
            img: "/assets/img/chees.jpg",
          },
          
     
    ]
  }, 
  {
    'data' : 'salads',
    'mini' : false,
    'cat':{"EN":'Salads',"RU":'Салаты'},
    'items': [
      {

        id: "sas2142",
        name: {"RU": "Салат со свеклой и козьим сыром", "EN": "Salad with beets and goat cheese"},
        title:{'EN':'', 'RU':""},
        price: 760,
        count: 1,
        grams: 220,
        img: "https://eda.yandex/images/14549513/6b2969815a0c411eb7145d49d1558601-450x300.jpeg",
      },
        {
            id: 41,
            name:{'EN':'Broken cucumber and salmon', 'RU':"Битый огурец и лосось"}, 
            title:{'EN':'Salmon, cucumbers, onions, mixed greens, cashew nuts', 'RU':"Лосось, огурцы, лук репчатый, зелень микс, орех кешью"}, 
            price: 910,
            count: 1,
            grams: 360,
            modifier:{'EN':['sashimi','on the grill'], 'RU':['сашими','на гриле']}, 
            img: "https://eda.yandex/images/1365461/5681b62da62948979fc0cd24460e795c-450x300.jpeg",
          },
          {
            id: 42,
            name:{'EN':'Greek salad with kalamata olives', 'RU':"Греческий салат с оливками каламата"}, 
            title:{'EN':'Baku tomatoes, cucumbers, bell peppers, red onions, mixed salad', 'RU':"Помидоры бакинские, огурцы, болгарский перец, красный лук, микс салатов"},
            price: 810,
            count: 1,
            grams: 310,
            img: "https://eda.yandex/images/1365461/055b5a8109214689be7236d7865805e2-450x300.jpeg",
          },
          {
            id: 43,
            name:{'EN':'Green Bowl', 'RU':"Зеленый боул"},
            title:{'EN':'Avocado, cucumber, chicken egg, chuca lettuce, spinach', 'RU':"Авокадо, огурец, яйцо куриное, чука салат, шпинат"}, 
            price: 980,
            count: 1,
            grams: 170,
            img: "https://eda.yandex/images/13806227/c256ce9db4354008af8cd73e34c09da4-450x300.jpeg",
          },
          {
            id: 45,
            name:{'EN':'Grilled shrimp Caesar', 'RU':"Цезарь с креветками на гриле"}, 
            title:{'EN':'Romano salad leaves, shrimp, cherry tomatoes, parmesan cheese, caesar sauce, wheat baguette croutons', 'RU':"Листья салата Романо, креветки, помидоры черри, сыр пармезан, соус цезарь, гренки из пшеничного багета"}, 
            price: 800,
            count: 1,
            grams: 250,
            img: "https://eda.yandex/images/2050703/f30a4073c5334ab48b3ac9c5f31a07c2-450x300.jpeg",
          },
          {
            id: 46,
            name:{'EN':'Caesar with grilled chicken breast', 'RU':"Цезарь с куриной грудкой на гриле"}, 
            title:{'EN':'Romano salad leaves, chicken fillet, cherry tomatoes, parmesan cheese, sauce', 'RU':"Листья салата Романо, куриное филе, помидоры черри, сыр пармезан, соус"},
            price: 650,
            count: 1,
            grams: 250,
            img: "/assets/img/caesarwithgrilledchickenbreast.jpeg",
          },
      

        
          
          {
            id: 'sd3',
            name:{'EN':'Green salad with crab', 'RU':"Зелёный салат с крабом"}, 
            title:{'EN':'Ruccola, cucumber, avocado, crab, sesame dressing, parmesan, cherry tomatoes', 'RU':"Руккола, огурец, авокадо, краб, кунжутный дрессинг, пармезан, помидоры черри"}, 
            price: 1100,
            count: 1,
            grams: 240,
            img: "/assets/img/greensaladwithcrab.jpeg",
          },
          {
            id: 'sd1',
            name:{'EN':'Burrata with tomatoes and spinach', 'RU':"Буррата с томатами и шпинатом"}, 
            title:{'EN':'Burrata cheese, tomatoes, spinach', 'RU':"Сыр буррата, томаты, шпинат"}, 
            price: 950,
            count: 1,
            grams: 120,
            img: "https://eda.yandex/images/13190335/5e234a36798646b591af3968d0d2836c-450x300.jpeg",
          },
         
          {
            id: 'sd6',
            name:{'EN':'Salad with shrimp, avocado and tomatoes', 'RU':"Салат с креветками, авокадо и томатами"}, 
            title:{'EN':'Shrimp, Baku tomatoes, avocado, cilantro, sour cream, olive oil, sesame', 'RU':"Креветки, помидоры бакинские, авокадо, кинза, сметана, оливковое масло, кунжут"}, 
            price: 980,
            count: 1,
            grams: 250,
            img: "https://eda.yandex/images/13058477/d50cadeae4124a43a001913ca60247de-450x300.jpeg",
          }
    ]
  },
  {
    'data' : 'brusshetta',
    'mini' : false,
    'cat':{"EN":'Bruschetta',"RU":'Брускетты'},
    'items': [

          {
            id: 62,
            name:{'EN': 'Bruschetta with crab and pickled tomatoes', 'RU':"Брускетта с крабом и маринованными томатами" },
            title:{'EN': 'Grain bread, crab, tomatoes, romano salad, spicy sauce', 'RU':"Хлеб зерновой, краб, помидоры, салат романо, спайси соус" } ,
            price: 920,
            count: 1,
            grams: 190,
            img: "/assets/items/Bruschettawithcrab.jpeg",
          },
          {
            id: 63,
            name:{'EN': 'With salmon and avocado', 'RU':"С лососем и авокадо" },
            title:{'EN': 'Grain bread, lightly salted salmon, avocado, tomato, creamy', 'RU':"Хлеб зерновой, лосось слабосоленый, авокадо, помидоры, сливочный" },
            price: 980,
            count: 1,
            grams: 220,
            img: "https://eda.yandex/images/931388/85d02d4831534b53bf63a382e89f0c52-450x300.jpeg",
          },
          {
            id: 'b1',
            name: {'EN': "Bruschetta with roast beef and red onions", 'RU': "Брускетта с ростбифом и красным луком"},
            title: {'EN': "Grain bread, roast beef, tomatoes, red onion, mustard, horseradish, olive oil, parsley", 'RU': "Хлеб зерновой, ростбиф (говядина), помидоры, красный лук, горчица, хрен, оливковое масло, петрушка"},
            price: 690,
            count: 1,
            grams: 190,
            img: "https://eda.yandex/images/13055084/a43a25323aed4b15b86b18c1cd550e6f-450x300.jpeg"
          },
          {
            id: 65,
            name:{'EN': 'With tomatoes and avocado', 'RU':"С томатами и авокадо" },
            title:{'EN': 'Grain bread, tomatoes, avocado, guacamole sauce, Romano salads, Frise', 'RU': "Хлеб зерновой, помидоры, авокадо, соус Гуакамоле, салаты Романо, Фризе"},
            price: 520,
            count: 1,
            grams: 165,
            img: "/assets/img/withtomatoesandavocado.jpeg",
          },
    ]
  },
  {
    'data': 'soap',
    'mini' : false,
    'cat':{"EN":'Soups',"RU":'Супы'},
    'items': [
        {
            id: 'so1',
            name:{'EN': 'Borscht with veal cheek and smoked prunes', 'RU':"Борщ с телячьей щёчкой и копченым черносливом"} ,
            title:{'EN': 'Salt, black pepper, sugar, garlic fraiche, dill, parsley, sour cream, green onions, borodino bread', 'RU':"Соль, перец черный, сахар, фреш чесночный, укроп, петрушка, сметана, лук зеленый, хлеб бородинский"} ,
            price: 650,
            count: 1,
            grams: 450,
            img: "/assets/img/borscht.jpeg",
          },
          {
            id: 86,
            name:{'EN': 'Chicken noodle soup', 'RU':"Суп-лапша из цыпленка"} ,
            title:{'EN': 'Chicken broth, vermicelli, chicken fillet, quail egg, herbs', 'RU':"Куриный бульон, вермишель, куриное филе, перепелиное яйцо, зелень"} ,
            price: 480,
            count: 1,
            grams: 450,
            img: "/assets/img/lap.jpg",
          }, 
          {
            id: 'so2',
            name:{'EN': 'Tom yam with shrimp and wood mushrooms', 'RU':"Том ям с креветками и древесными грибами"} ,
            title:{'EN': 'Squid, wood mushrooms, basmati rice, sesame oil, coconut milk, tomato, lime, shrimp, tomato paste, ginger, oyster mushrooms, mussels, cilantro', 'RU':"Кальмар, грибы древесные, рис басмати, масло кунжутное, молоко кокосовое, помидоры, лайм, креветки, паста томатная, имбирь, вешенки, мидии, кинза"} ,
            price: 900,
            count: 1,
            grams: 580,
            img: "/assets/img/tomyamwithshrimpandwoodmushrooms.jpeg",
          },
          {
            id: 'so3',
            name:{'EN': 'Salmon, sea bass and cod soup', 'RU':"Уха из лосося, сибаса и трески"} ,
            title:{'EN': 'Fish broth, mussels, salmon, sea bass, cod, potatoes, tomatoes, garlic fresh, dill, parsley', 'RU':"Бульон рыбный, мидии, лосось, сибас, треска, картофель, томаты, чесночный фреш, укроп, петрушка"} ,
            price: 890,
            count: 1,
            grams: 450,
            img: "/assets/items/Salmonseabassandcodfissoup.jpeg",
          },
          {
            id: 'so4',
            name:{'EN': 'Lentil cream soup with artichokes and pickled onions', 'RU':"Крем-суп из чечевицы с артишоками и маринованным лучком"} ,
            title:{'EN': 'Lentils, carrots, onions, potatoes, artichokes, pearl onions, green onions, seeds, ground olives, olive oil, vegetable oil, garlic, salt, pepper', 'RU':"Чечевица, морковь, лук репчатый, картофель, артишоки, лук жемчужный, лук зеленый, семечки, земля из маслин, оливковое масло, масло растительное, чеснок, соль, перец"} ,
            price: 550,
            count: 1,
            grams: 330,
            img: "/assets/items/so4.jpeg",
          },
    ]
  },
  {
    'data' : 'pasta',
    'mini' : false,
    'cat':{"EN": 'Pasta and risotto',"RU": 'Паста и ризотто'},
    'items': [
        {
            id: 'p1',
            name:{'EN':'Spaghetti with crab in tomato sauce', 'RU':"Спагетти с крабом в томатном соусе"}, 
            title:{'EN':'Spaghetti, crab, chicken broth, basil, tomato sauce, butter', 'RU':"Спагетти, краб, куриный бульон, базилик, соус томатный, масло сливочное"}, 
            price: 1050,
            count: 1,
            grams: 300,
            img: "https://eda.yandex/images/13190335/54837ea8097748f58c3dd6c2992df7b6-450x300.jpeg",
          },
          {
            id: 'p2',
            name:{'EN':'Tagliatelle with seafood', 'RU':"Тальятелле с морепродуктами"}, 
            title:{'EN':'Tagliatelle, calamari, shrimp, mussels, octopus, white wine, chicken broth, rosemary, thyme, olive oil, vegetable oil, Parmesan', 'RU':"Тальятелле, кальмары, креветки, мидии, осьминог, вино белое, куриный бульон, розмарин, тимьян, масло оливковое, масло растительное, пармезан"}, 
            price: 990,
            count: 1,
            grams: 390,
            img: "https://eda.yandex/images/1219753/9ab891f2b3fc43bf961771aabd0e433e-450x300.jpeg",
          },   {
            id: 'p3',
            name:{'EN':'Risotto with porcini mushrooms', 'RU':"Ризотто с белыми грибами"}, 
            title:{'EN':'Arborio rice, porcini mushrooms', 'RU':"Рис арборио, белые грибы"}, 
            price: 1200,
            count: 1,
            grams: 190,
            img: "https://eda.yandex/images/931388/3aa89fcbcae943128735a629256d712e-450x300.jpeg",
          },   {
            id: 'p4',
            name:{'EN':'Penne with beef, porcini mushrooms and truffle sauce', 'RU':"Пенне с говядиной, белыми грибами и трюфельным соусом"}, 
            title:{'EN':'Penne, beef, parmesan cheese, porcini mushrooms, white wine, cream, tomatoes, truffle oil, olive oil', 'RU':"Пенне, говяжья вырезка, сыр пармезан, белые грибы, вино белое, сливки, помидоры, масло трюфельное, масло оливковое"}, 
            price: 1250,
            count: 1,
            grams: 350,
            img: "https://eda.yandex/images/13912834/ca45dffbeb194e1ea29cd1b9754ac2e0-450x300.jpeg",
          },        {
            id: 'p7',
            name:{'EN':'Spaghetti with vongole', 'RU':"Спагетти с вонголе"}, 
            title:{'EN':'Vongole, white wine, salt, pepper, shallot, garlic puree, chicken broth, butter, parsley', 'RU':"Вонголе, вино белое, соль, перец, шалот, чесночное пюре, бульон куриный, сливочное масло, петрушка"}, 
            price: 750,
            count: 1,
            grams: 330,
            img: "https://eda.yandex/images/3806315/0322c3e249c142b0b99b8ecdd7e931e6-450x300.jpeg",
          },   {
            id: 'p8',
            name:{'EN':'Risotto with beef tartare', 'RU':"Ризотто с тартаром из говядины"}, 
            title:{'EN':'Chicken broth, salt, pepper, butter, cream, beef tartare, green peas, watercress, olive oil, truffle oil', 'RU':"Куриный бульон, соль, перец, масло сливочное, сливки, тартар из говядины, горошек зеленый, кресс-салат, масло оливковое, масло трюфельное"}, 
            price: 1160,
            count: 1,
            grams: 190,
            img: "https://eda.yandex/images/2370127/1f907a2519654f42839910c3dbd031c3-450x300.jpeg",
          },   
          {
            id: 'p10',
            name:{'EN':'Spaghetti Bolognese', 'RU':"Спагетти Болоньезе"}, 
            title:{'EN':'Spaghetti, bolognese sauce, arabiata pilati sauce, parmesan cheese, olive oil, microgreens, olive ground', 'RU':"Спагетти, соус болоньезе, соус арабьята пилати, сыр пармезан, масло оливковое, микрозелень, земля из маслин"}, 
            price: 790,
            count: 1,
            grams: 250,
            img: "https://eda.yandex/images/1472406/5be00cf5216346d7a22655416a90e7ac-450x300.jpeg",
          },
          
    ]
  },  
  {
        'data' : 'noodles',
        'mini' : false,
        'cat':{"EN":'Noodles',"RU":'Лапша'},
        'items': [
          {
            id: 'p5',
            name:{'EN':'Buckwheat noodles with chicken in Asian sauce', 'RU':"Гречневая лапша с курицей в азиатском соусе"}, 
            title:{'EN':'Buckwheat noodles, chicken thigh, bell peppers, carrots, zucchini, pea pods, Singapore sauce, sesame', 'RU':"Лапша гречневая, куриное бедро, болгарский перец, морковь, цукини, стручки гороха, сингапурский соус, кунжут"}, 
            price: 780,
            count: 1,
            grams: 300,
            img: "https://eda.yandex/images/1473782/41b66dcdfdb941d59c5cd30b7dc04684-450x300.jpeg",
          }, 
          {
            id: 'p6',
            name:{'EN':'Rice noodles with tiger shrimps', 'RU':"Рисовая лапша с тигровыми креветками"}, 
            title:{'EN':'Rice noodles, tiger shrimp, bell peppers, carrots, zucchini, egg, Singapore sauce, cilantro', 'RU':"Рисовая лапша, тигровые креветки, болгарский перец, морковь, цукини, яйцо, сингапурский соус, кинза"}, 
            price: 800,
            count: 1,
            grams: 320,
            img: "https://eda.yandex/images/3534679/c4b043de7c194c62adb9ca24c8ef9ba6-450x300.jpeg",
          },
        ]
  },
  {
    'data' : 'fishSeafood',
    'mini' : false,
    'cat':{"EN":'Fish and seafood',"RU":'Рыба и морепродукты'},
    'items': [
      {
        id: "125adpowjpodjapo",
        name:{'EN': 'Crab cakes with fresh vegetables', 'RU':"Крабовые котлеты со свежими овощами"},
        title:{'EN': '', 'RU':""},
        modifier:{'EN':['on the grill', 'steamed'], 'RU':['на гриле','на пару']},
        price: 1300,
        count: 1,
        grams: 245,
        img: "https://eda.yandex/images/1463280/b7df6243da7f461da2a474506c708a16-450x300.jpeg",
      },
      {
        id: "125a321312dpowjpodjapo",
        name:{'EN': 'Sea bass fillet with zucchini', 'RU':"Филе сибаса с цукини"},
        title:{'EN': '', 'RU':""},

        price: 960,
        count: 1,
        grams: 275,
        img: "https://eda.yandex/images/13806227/b56e32be6a6e4de789b0461cef3f9f05-450x300.jpeg",
      },
      {
        id: "12225a321312dpowjpodjapo",
        name:{'EN': 'Tuna steak with guacamole', 'RU':"Стейк из тунца с гуакамоле"},
        title:{'EN': '', 'RU':""},

        price: 1200,
        count: 1,
        grams: 200,
        img: "https://eda.yandex/images/3806466/092024d966bb4e7390ac00ae358b6c99-400x400nocrop.jpeg",
      },
      {
        id: "12225a321312dpowjpodjapo",
        name:{'EN': 'Fried squid with tomatoes', 'RU':"Жареный кальмар с томатами"},
        title:{'EN': '', 'RU':""},

        price: 1100,
        count: 1,
        grams: 220,
        img: "https://eda.yandex/images/3550919/e3c8ebb9f049414eb2a497c906e9d7c9-450x300.jpeg",
      },

        {
          id: 125,
          name:{'EN': 'Salmon steak with vegetable salsa', 'RU':"Стейк лосося с овощной сальсой"},
          title:{'EN': 'Salmon fillet, tomato salsa, avocado, cucumber vegetable oil', 'RU':"Филе лосося, сальса из томатов, авокадо, огурец масло растительное"},
          modifier:{'EN':['on the grill', 'steamed'], 'RU':['на гриле','на пару']},
          price: 1500,
          count: 1,
          grams: 200,
          img: "/assets/img/salmonsteakwithvegetablesalsa.jpeg",
        },
        {
          id: 81,
          name:{'EN': 'Mussels in wine sauce', 'RU':"Мидии в винном соусе"} ,
          title:{'EN': 'Mussels, chicken broth, wine, coconut milk, rosemary, thyme, cilantro', 'RU':"Мидии, куриный бульон, вино, кокосовое молоко, розмарин, тимьян, кинза"},
          price: 880,
          count: 1,
          grams: 500,
          img: "https://eda.yandex/images/3805444/8e14cf41f42a49bf9dc19c974cda0f7c-450x300.jpeg",
        },
        {
            id: 80,
            name:{'EN': 'Grilled shrimp with spicy sauce', 'RU':"Креветки на гриле с соусом спайси"} ,
            title:{'EN': 'Shrimp, soy sauce, sesame oil, spicy sauce, sesame seeds, bamboo leaf', 'RU':"Креветки, соевый соус, масло кунжутное, спайси соус, кунжут, лист бамбука"},
            price: 900,
            count: 1,
            grams: 150,
            img: "/assets/img/grilledshrimpwithspicysauce.jpeg",
        },  
          
        
         {
          id: 2343,
          name: {'EN': 'Black cod on a bed of spinach', 'RU': 'Черная треска на подушке из шпината'},
          title: {'EN': 'Baked black cod fillet served on a bed of poached spinach surrounded by walnut sauce and almond slices', 'RU': 'Запеченное филе черной трески подается на подушке из припущенного шпината в окружении орехового соуса и слайсов миндаля'},
          price: 1030,
          count: 1,
          grams: 180,
          img: "https://eda.yandex/images/3805363/5d493f8cb92746e5b390d7ade7a8a6e4-450x300.jpeg"
         }
    ]
  },
  {
    'data': 'meatPoultry',
    'mini': false,
    'cat':{"EN":'Meat and poultry',"RU":'Мясо и птица'},
    'items': [

          {
            id: 72,
            name:{'EN': 'Chicken curry with rice', 'RU':"Курица карри с рисом" },
            title:{'EN': 'Chicken fillet, rice, curry sauce', 'RU':"Куриное филе, рис, карри соус" },
            price: 920,
            count: 1,
            grams: 280,
            img: "https://eda.yandex/images/1473782/8cf7086ffe6149fbab407c13ca9ec17e-450x300.jpeg",
          },
        {
          id: 72,
          name:{'EN': 'Marbled beef cutlets', 'RU':"Котлеты из мраморной говядины" },
          title:{'EN': '', 'RU':"" },
          price: 990,
          count: 1,
          grams: 300,
          img: "https://eda.yandex/images/13190335/7b6ab4b8b059497d9eff2211154876ac-400x400nocrop.jpeg",
        },
          {
            id: 73,
            name:{'EN': 'Ribeye steak with grilled corn', 'RU':"Рибай стейк с кукурузой на гриле" },
            title:{'EN': 'Beef loin, corn cob', 'RU':"Говяжья вырезка, початок кукурузы" },
            price: 3400,
            count: 1,
            grams: 380,
            img: "https://eda.yandex/images/3506707/a89969f78e974f268b0610de54dcded2-450x300.jpeg",
          },
          {
            id: 75,
            name:{'EN': 'Grilled filet mignon with zucchini', 'RU':"Филе миньон с цукини на гриле" },
            title:{'EN': 'Beef loin, zucchini, mushroom sauce, vegetable oil', 'RU':"Говяжья вырезка, цукини, грибной соус, масло растительное" },
            price: 2200,
            count: 1,
            grams: 350,
            img: "https://eda.yandex/images/2353725/fbab8077fb2a40f1960caacdc08fcca0-450x300.jpeg",
          },
          {
            id: 'm2',
            name:{'EN': 'Stewed veal cheek with mashed potatoes and tomatoes', 'RU':"Томлённая телячья щёчка с пюре и томатами" },
            title:{'EN': 'Mashed potatoes, demi-glace sauce, Uzbek tomatoes, cilantro, wine, thyme, garlic, onions, carrots, salt', 'RU':"Пюре картофельное, соус демиглас, помидоры узбекские, кинза, вино, тимьян, чеснок, лук, морковь, соль" },
            price: 1150,
            count: 1,
            grams: 340,
            img: "https://eda.yandex/images/13055084/b23ae4bcc94a43b5b8b261c624cb384f-450x300.jpeg",
          },
          {
            id: 'm3',
            name:{'EN': 'Beef Stroganoff', 'RU':"Бефстроганов" },
            title:{'EN': 'Beef, cream, mushrooms, walnut sauce, pickles, watercress, almond slices', 'RU':"Говядина, сливки, шампиньоны, соус ореховый, огурцы маринованные, кресс-салат, слайсы миндаля" },
            price: 970,
            count: 1,
            grams: 340,
            img: "https://eda.yandex/images/13439948/75448d004dab456080ab38c9426a1e2d-450x300.jpeg",
          },
          {
            id: 'm4',
            name: {
              'EN': 'Chicken with Cole Slow', 'RU': 'Цыпленок с Коул Слоу'
            },
            title: {
              'EN': 'Baked chicken with truffle coleslaw', 'RU': 'Запеченный цыпленек с трюфельным коул слоу'
            },
            price: 1250,
            count: 1,
            grams: 260,
            img: 'https://eda.yandex/images/1472406/c67dd898282c4815ae426d33726e6ced-450x300.jpeg'
          }
        
         
    ]
  }, 
  {
    'data' : 'sideDishes',
    'mini' : false,
    'cat':{"EN":'Side dishes',"RU":'Гарниры'},
    'items': [
        {
            id: 66,
            name:{'EN': 'Fried potatoes with oyster mushrooms', 'RU':"Жареный картофель с вешенками" },
            title:{'EN': 'Potatoes, oyster mushrooms, onions, parsley, garlic oil, salt, pepper', 'RU':"Картофель, грибы вешенки, лук, петрушка, чесночное масло, соль, перец" },
            price: 410,
            count: 1,
            grams: 200,
            img: "https://eda.yandex/images/1447609/031bdfa19c7c4038b06af56a6d500d3d-450x300.jpeg",
          },
          {
            id: 67,
            name:{'EN': 'Roasted spinach with tomatoes', 'RU':"Жареный шпинат с томатами" },
            title:{'EN': 'Spinach, garlic oil, cherry tomatoes, salt, pepper', 'RU': "Шпинат, чесночное масло, томаты черри, соль, перец"},
            price: 410,
            count: 1,
            grams: 90,
            img: "https://eda.yandex/images/3784951/b8170ab76146432aa0e2e099f10e5e98-450x300.jpeg",
          },
          {
            id: 68,
            name:{'EN': 'Mashed potatoes', 'RU':"Картофельное пюре" },
            title:{'EN': 'Potatoes, butter, cream', 'RU':"Картофель, сливочное масло, сливки" },
            price: 360,
            count: 1,
            grams: 150,
            img: "https://eda.yandex/images/3806466/e27e11ae989a4800b6f6346adee5577f-450x300.jpeg",
          },
          {
            id: 69,
            name:{'EN': 'Grilled corn', 'RU':"Кукуруза на гриле" },
            title:{'EN': 'Corn', 'RU':"Кукуруза" },
            price: 410,
            count: 1,
            grams: 200,
            img: "https://eda.yandex/images/3806315/e87cfe9fc265416aa9657619ffc42034-450x300.jpeg",
          },
          {
            id: 'v1',
            name:{'EN': 'Cabbage steak with red caviar', 'RU':"Стейк из капусты с красной икрой" },
            title:{'EN': 'Grilled cabbage steak served with cream sauce and red caviar', 'RU':"Стейк из капусты на гриле подается со сливочным соусом и красной икрой" },
            price: 750,
            count: 1,
            grams: 250,
            img: "/assets/items/v1.jpeg",
          },
    ]
  }, 
  {
    'data' : 'desserts',
    'mini' : false,
    'cat': {"EN": 'Desserts', "RU": 'Десерты'},
    'items': [
        {
            id: 89,
            name:{'EN': 'Warm apple pie with an ice cream scoop', 'RU':"Теплый яблочный пирог с шариком мороженого"} ,
            title:{'EN': 'Homemade apple and puff pastry pie, ice cream scoop, nuts', 'RU':"Домашний пирог из яблок и слоеного теста, шарик мороженого, орехи"} ,
            price: 540,
            count: 1,
            grams: 210,
            img: "/assets/img/warmapplepiewithanicecreamscoop.jpeg",
          },
          {
            id: 'ds2',
            name:{'EN': 'Miles with patisserie cream and fresh berries', 'RU':"Мильфей с кремом патисьер и свежими ягодами"},
            title:{'EN': 'Puff pastry, cream, raspberries, strawberries, blueberries, blackberries, freeze-dried raspberries', 'RU':"Тесто слоеное, крем, малина, клубника, голубика, ежевика, малина сублимированная"},
            price: 800,
            count: 1,
            grams: 160,
            img: "/assets/img/mileswithpatisseriecreamandfreshberries.jpeg",
          },

          {
            id: 'ds5',
            name: {'EN': 'Chocolate fondant with vanilla ice cream', 'RU': 'Шоколадный фондан с ванильным мороженым'},
            title: {'EN': '', 'RU': ''},
            price: 660,
            grams: 180,
            count: 1,
            img: '/assets/img/chocolatefondant.jpeg'
          }
         
         
    ]
  },
  {
        'data' : 'children',
        'mini' : false,
        'cat':{"EN":'Children`s menu',"RU":'Детское меню'},
        'items': [
          {
            id: '55d2',
            name:{'EN': 'Vegetable salad', 'RU':"Салат овощной" },
            title:{'EN': '', 'RU':"" },
            price: 300,
            count: 1,
            grams: 110,
            img: "",
          },
            {
                id: 55,
                name:{'EN': 'Beef stroganoff with mashed potatoes', 'RU':"Бефстроганов из говядины с картофельным пюре" },
                title:{'EN': 'Beef loin, mashed potatoes, cream sauce', 'RU':"Говяжья вырезка, картофельное пюре, сливочный соус" },
                price: 700,
                count: 1,
                grams: 240,
                img: "/assets/img/beefstroganoffchild.jpeg",
              },
              {
                id: 56,
                name:{'EN': 'Chicken cutlets with mashed potatoes', 'RU':"Куриные котлеты с картофельным пюре" },
                title:{'EN': 'Minced chicken, mashed potatoes, butter', 'RU':"Куриный фарш, картофельное пюре, сливочное масло" },
                price: 700,
                count: 1,
                grams: 240,
                img: "/assets/img/chickencutletswithmashedpotatoes.jpeg",
              },
              {
                id: '56D1',
                name:{'EN': 'Girandole in creamy sauce with Parmesan cheese', 'RU':"Джирандоле в сливочном соусе с сыром пармезан" },
                title:{'EN': '', 'RU':"" },
                price: 380,
                count: 1,
                grams: 210,
                img: "https://eda.yandex/images/3596693/cbb90f9cc80e41439cdba76970191082-450x300.jpeg",
              },
              {
                id: 57,
                name:{'EN': 'Chicken broth with noodles and vegetables', 'RU':"Куриный бульон с лапшой и овощами" },
                title:{'EN': 'Chicken broth, chicken filet, noodles, vegetables', 'RU':"Куриный бульон, куриное филе, лапша, овощи" },
                price: 260,
                count: 1,
                grams: 230,
                img: "/assets/items/Chickenbouillon.jpeg",
              },

        ]
  },   
 
];






module.exports = { items };